3YOURMIND/kotti

components/Sidebar.vue
layouts/default.vue

Fix the scrollbar in the layout.
**Before**
**After**

fix(scrollbar): fix scrollbar on every system

---

.gitignore
packages/kotti-avatar-group/src/avatar-group.vue
packages/kotti-avatar/src/avatar.vue
packages/kotti-button-group/src/button-group.vue
packages/kotti-comment/src/Comment.vue
packages/kotti-comment/src/CommentInput.vue
packages/kotti-comment/src/CommentReply.vue
packages/kotti-style/src/_avatar.scss
packages/kotti-style/src/_buttons.scss
packages/kotti-style/src/_comments.scss
packages/kotti-style/src/index.scss
www/assets/json/submenu.js
www/components/Navbar.vue
www/layouts/default.vue
www/pages/components/avatars.vue
www/pages/patterns/comments.vue

Created new comments pattern for review

Feat pattern comment

---

docs/pages/components/inputs.vue
packages/kotti-input/src/Input.vue

Add `forLabel` props for `KtInput`

Add forLabel to support for attributes, close #38

---

packages/kotti-inline-edit/index.js
packages/kotti-inline-edit/src/InlineEdit.vue

Because I need support for new line in single paragraphs
I can't find docs for this component to update

added dangerous parser override to KtInlineEdit as well

---

docs/pages/components/tables.vue
packages/kotti-table/src/Table.vue
packages/kotti-table/src/TableColumn.js
packages/kotti-table/src/TableHeader.vue
packages/kotti-table/src/logic/column.js

it is now possible to enable column drag and drop

added KtTable column order function

---

packages/kotti-table/src/Table.vue

Change disabled row opacity to visually distinguish it

---

docs/pages/foundations/layout.vue

Untested, but only modifies markdown anyway.

Add Link to Responsive Classes to Docs

---

docs/pages/components/tables.vue
packages/kotti-table/src/TableColumn.js

thClass is now properly implemented on KtTableColumn

thClass implementation + typo fix

---

docs/assets/json/submenu.js
docs/pages/components/checkbox.vue
packages/index.js
packages/kotti-checkbox/index.js
packages/kotti-checkbox/src/Checkbox.vue

Add a component for checkboxes. 
Also add the documentation for it and add it to the NavBar.

Add checkbox component (fix #71)

---

package.json

In semver, the first number stands for major change, the second for minor, the third for patch.
Caret "^" means only update patches, tild "~" means update also minor version.
Minor version does not break anything so let's use minor version updates.

improvement: use tilds ~ for dependencies version.

---

packages/kotti-single-select/src/SingleSelect.vue

KtSelecr Upgrade:
- Add triger focus event in handleInputFocus method
- v-bind :autocomplete attribute to this.$attrs.autcomplete

Kt select upgrade

---

docs/pages/patterns/navbar.vue

costed me 2 hours of struggle when trying Kotti the first time. ;-)

correct KtNavbar example docs

---

docs/pages/components/selects.vue
packages/kotti-single-select/src/SingleSelect.vue

The title speaks for itself :)
Nevertheless, A small addition addition of functionality to pass make available and pass on a `disabled` prop to the input tag of KtSelect

add disabled prop to KtSelect

---

docs/pages/components/popovers.vue
packages/kotti-popover/src/Popover.vue

revert the clickaway behaviour as it was causing issues with closing popovers

revert the clickaway behaviour

---

docs/pages/components/dropdowns.vue
packages/index.js
packages/kotti-dropdown-button/KtDropdownButton.vue
packages/kotti-dropdown-button/index.js

This PR introduce a dropdown button feature.
It uses the actual dropdown implementation and uses a CSS enhanced button group.
Low  urgence on this one, we can take time.

Add dropdown button

---

docs/components/ShowCase.vue
docs/pages/components/tables.vue
package.json
packages/kotti-table/src/Table.vue
packages/kotti-table/src/logic/column.js
packages/kotti-table/src/logic/disable.js
packages/kotti-table/src/logic/expand.js
packages/kotti-table/src/logic/order.js
packages/kotti-table/src/logic/select.js
yarn.lock

fix(KtTable-selected-expandMultiple): fixed selected binding

---

packages/kotti-navbar/src/KtNavbarMenu.vue
packages/kotti-table/src/TableBody.js
packages/kotti-user-menu/src/UserMenu.vue

added three data-test-attributes for testing: Navbar-menu and footer and Tables.

Data test up

---

packages/kotti-navbar/src/KtNavbarMenu.vue
packages/kotti-user-menu/src/UserMenu.vue

first data-test attributes in User-Panel

data-test-attributes

---

packages/kotti-table/src/TableBody.js

I made a mistake in my last pull-request.

changed row.index to row.title

---

package.json
yarn.lock

Add eslint-plugin-vue to package.json so build and publish don't fail

feat(update-kotti-packages)

---

packages/kotti-avatar-group/src/AvatarGroup.vue
packages/kotti-style/_avatar.scss

change justify-content to be centered
added computed prop instead of v-if/v-for /
(linter suggestion and I agree)
#137

enhance/refact(#137): KtAvatarGroup

---

packages/kotti-table/src/Table.vue
packages/kotti-table/src/TableRow.js
packages/kotti-table/src/logic/select.js

initially this was a bugfix but turns out it's not a bug. issue #130 is closed now.
removed dead code
removed extra arg
cleaner logic in toggleAllSelected
removed eslint ignores after recent chore update
fixed minor typo

minor(KtTable):

---

package.json
packages/index.js
packages/kotti-accordion/KtAccordion.vue
packages/kotti-button-group/src/ButtonGroup.vue
packages/kotti-button/src/button.vue
packages/kotti-dropdown-button/KtDropdownButton.vue
packages/kotti-input-number/src/InputNumber.vue
packages/kotti-popover/KtPopover.vue
packages/kotti-popover/KtPopoverItem.vue
packages/kotti-radio-group/src/RadioGroup.vue
packages/kotti-single-select/src/SingleSelect.vue
packages/kotti-table/src/TableHeader.vue

This PR fixes missing exports in the index.js and install function, and it also returns the explicit import of variables in the components, which is required for 3rd party users.

Fixed to variables and install function

---

packages/kotti-input-number/src/InputNumber.vue

This PR fixes the KtInputNumber to handle floats correctly, and it fixes a bug with currentValue not being updated correctly.

Fixes for forms

---

docs/assets/css/main.scss
docs/pages/components/tables.vue
packages/kotti-table/src/Table.vue
packages/kotti-table/src/logic/column.js
packages/kotti-table/src/logic/filter.js
packages/kotti-table/src/logic/hide.js
packages/kotti-table/src/logic/order.js
packages/kotti-table/src/logic/row.js

FT:
1) drag columns around on the dragable table in the docs 
expected: are draggable and consistent with the original behavior (can drag any column to any place except to the last column
2) in general, better check that all examples in docs work as described (should take ~5mins)

149 fix broken dragability on kt table

---

packages/kotti-input-number/src/InputNumber.vue

prohibit emission of input with null values

enhance(173): prohibit KtInputNumber from emitting input with null payload

---

packages/kotti-datepicker/index.js

Can be tested with https://gitlab.3yourmind.com/dev/yoda/-/merge_requests/97

fix wrong datepicker import

---

packages/kotti-table/src/Table.vue
packages/kotti-table/src/logic/column.js
packages/kotti-table/src/logic/order.js
packages/kotti-table/src/logic/sort.js

Fix slots overwriting columns prop props

---

package.json
yarn.lock

Just bumping yoco version :+1: 
Only one review needed

chore: bump yoco

---

packages/kotti-navbar/src/KtNavbar.vue

Fix navbar

---

package.json
yarn.lock

chore: bump

---

packages/kotti-style/tokens.css
tokens/colors.js

feat: add a new token

---

README.md

Old readme was very outdated and contained some hardly useful information.
You can check out [the preview here](https://github.com/3YOURMIND/kotti/blob/217-improve-readme/README.md)

documentation(#217): Improve & Update Readme

---

packages/next/kotti-field/hooks.ts

Mostly caused by the hooks refactor. It makes it way harder to see duplicate keys in the returns.
#224

fix(#224): KtForm isDisabled not affecting KtFields Within

---

docs/pages/components/form.vue

documentation(#222): Simplify & Clean-Up Forms

---

README.md
package.json
packages/kotti-ui/package.json
packages/kotti-ui/rollup.config.js
packages/kotti-ui/source/index.ts
packages/kotti-ui/source/kotti-style/index.scss
packages/sass-node-modules-importer/README.md
packages/sass-node-modules-importer/package.json
packages/sass-node-modules-importer/source/find-node-modules.d.ts
packages/sass-node-modules-importer/source/index.ts
packages/sass-node-modules-importer/source/logger.ts
packages/sass-node-modules-importer/source/resolvers/directory.ts
packages/sass-node-modules-importer/source/resolvers/file.ts
packages/sass-node-modules-importer/source/types.ts
packages/sass-node-modules-importer/tsconfig.json
yarn.lock

This commit adds a custom sass importer that’s able to properly resolve node_modules, package.json style property, etc.

feature(sass-node-modules-importer): First Implementation

---

packages/kotti-ui/source/index.ts
packages/kotti-ui/source/kotti-popover/index.ts

This exports `KtPopoverItem` and that's it!

feature: export KtPopoverItem

---

packages/documentation/pages/components/form-fields.vue
packages/kotti-ui/source/next/kotti-field-number/KtFieldNumber.vue
packages/kotti-ui/source/next/kotti-field-number/constants.ts
packages/kotti-ui/source/next/kotti-field-number/types.ts

~~TBD: Should we make this a `hideChangeButtons` flag instead?~~
Answer: Yes

feature(#242): Add Show Change Buttons

---

packages/documentation/pages/components/form-fields.vue
packages/kotti-ui/source/next/kotti-field-radio-group/KtFieldRadioGroup.vue
packages/kotti-ui/source/next/kotti-field-toggle/KtFieldToggleGroup.vue
packages/kotti-ui/source/next/kotti-field-toggle/constants.ts
packages/kotti-ui/source/next/kotti-field-toggle/types.ts

feature(#274): Add isInline to KtFieldToggleGroup

---

packages/documentation/pages/components/form-fields.vue
packages/kotti-ui/source/index.ts
packages/kotti-ui/source/next/kotti-field-password/KtFieldPassword.vue
packages/kotti-ui/source/next/kotti-field-password/constants.ts
packages/kotti-ui/source/next/kotti-field-password/index.ts
packages/kotti-ui/source/next/kotti-field-password/types.ts

feature(#227): Implement KtFieldPassword

---

packages/kotti-ui/source/kotti-col/index.ts
packages/kotti-ui/source/kotti-row/index.ts

fix(#289): Check Slot Before Calling It

---

packages/kotti-ui/source/next/kotti-field-number/KtFieldNumber.vue

improvement(#307): Left-align KtFieldNumber when Appropriate

---

packages/kotti-ui/source/next/kotti-field-number/KtFieldNumber.vue

improvement(#309): Use Tabular Nums for Better Readability/Typography

---

packages/kotti-ui/source/next/kotti-field-date/hooks.ts
packages/yoco/source/types.ts
packages/yoco/svg/calendar_clock.svg

feature(#314): Add Yoco.Icon.CALENDAR_CLOCK

---

packages/kotti-ui/source/kotti-navbar/KtNavbar.vue
packages/kotti-ui/source/kotti-navbar/components/NavbarQuickLink.vue
packages/kotti-ui/source/kotti-user-menu/KtUserMenu.vue

Small adjustments for theming :)

Navbar adjustment

---

packages/documentation/pages/components/form-fields.vue
packages/kotti-ui/source/next/kotti-field-radio-group/KtFieldRadioGroup.vue
packages/kotti-ui/source/next/kotti-field-radio-group/types.ts

feature(KtFieldRadioGroup): Add tooltip option on options

---

packages/documentation/components/NavBar.vue
packages/documentation/shims-svg.d.ts

logo now doesn't fall to alt in default layout in docs

fix(defaultLayout): provided logourl to KtNavBar

---

packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelect.vue

Fixes a minor bug introduced in #357

fix(KtFieldMultiSelect): Use Array as Value Type

---

packages/kotti-ui/source/kotti-navbar/KtNavbar.vue
packages/kotti-ui/source/kotti-navbar/components/NavbarLogo.vue

Co-Authored-By: Florian Wendelborn <1133858+FlorianWendelborn@users.noreply.github.com>
Split from #349

refactor(KtNavbar): Remove Dead Code

---

packages/documentation/pages/usage/components/popover.vue
packages/kotti-ui/source/kotti-popover/KtPopover.vue
packages/kotti-ui/source/kotti-popover/components/IconTextItem.vue

Write a new prop data-set in internal component IconTextItem to track actions on items.

Feature enable popover text icon items to be tracked with data test

---

packages/kotti-ui/source/kotti-popover/KtPopover.vue
packages/kotti-ui/source/kotti-popover/components/IconTextItem.vue

Figma (also linked in documentation of course): <https://www.figma.com/file/0yFVivSWXgFf2ddEF92zkf/Kotti-Design-System?node-id=95%3A552>

improvement(KtPopover): Align with Design when Using Options

---

packages/documentation/pages/examples/layouts.vue
packages/documentation/pages/usage/layouts/navbar.vue
packages/documentation/pages/usage/layouts/user-menu.vue
packages/kotti-ui/source/kotti-user-menu/KtUserMenu.vue

* Scope Styles
* Minor Refactor
* Fix Example not Being Closable
* Rename Classes to BEM
Can be tested via `Layouts -> Navbar -> Open Example`

fix(KtUserMenu): Scope Styles

---

packages/kotti-ui/source/kotti-field/KtField.vue

Aim: increase size of helptext icon in form fields to 1.4em to make it more visible
Internal issue reference: https://3yourmind.atlassian.net/browse/B3-9307

improvement(KtField): increase size of help text icon in form fields

---

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue

fix(KtFieldNumber): Use Current Value

---

packages/kotti-ui/source/kotti-breadcrumb/KtBreadcrumb.vue
packages/kotti-ui/source/kotti-breadcrumb/index.ts
packages/kotti-ui/source/kotti-breadcrumb/types.ts
packages/kotti-ui/source/types/kotti.ts

refact(KtBreadcrumb): typescript, composition api

---

packages/documentation/pages/usage/components/avatar.vue
packages/documentation/pages/usage/components/table.vue
packages/kotti-ui/source/kotti-avatar-group/KtAvatarGroup.vue
packages/kotti-ui/source/kotti-avatar-group/index.ts
packages/kotti-ui/source/kotti-avatar-group/types.ts
packages/kotti-ui/source/kotti-avatar/KtAvatar.vue
packages/kotti-ui/source/kotti-avatar/index.ts
packages/kotti-ui/source/kotti-avatar/types.ts
packages/kotti-ui/source/kotti-comment/KtCommentInput.vue
packages/kotti-ui/source/kotti-comment/components/CommentReply.vue
packages/kotti-ui/source/kotti-user-menu/KtUserMenu.vue
packages/kotti-ui/source/types/kotti.ts
packages/yoco/source/types.ts
packages/yoco/svg/user_solid.svg

Needs to somehow be merged with #418. This is an older draft I have from attempting the same thing.

refactor(KtAvatar): composition api, tippy, scoped SCSS

---

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue

Simple typo fix I enoutered while investigating #347

fix(KtFieldNumber): fix typo in thrown error

---

packages/kotti-ui/source/kotti-comment/KtComment.vue

Set KtAvatar size in KtComment to small

---

packages/documentation/pages/usage/components/filters.vue
packages/documentation/pages/usage/components/form-fields.vue
packages/kotti-ui/package.json
packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue
packages/kotti-ui/source/kotti-field-number/constants.ts
packages/kotti-ui/source/kotti-field-number/utilities.ts
packages/kotti-ui/source/kotti-filters/components/FilterRow.vue
yarn.lock

This replaces all relevant math with `big.js`

fix(#465): KtFieldNumber Floating Point

---

packages/documentation/pages/usage/components/form-fields.vue
packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelect.vue
packages/kotti-ui/source/kotti-field-select/constants.ts
packages/kotti-ui/source/kotti-field-select/types.ts

feature(#481): Add maximumSelectable Prop to KtFieldMultiSelect

---

packages/documentation/pages/foundations/units.vue
packages/documentation/pages/usage/components/form.vue
packages/documentation/pages/usage/styles/form-fields.scss
packages/kotti-ui/source/kotti-actionbar/KtActionbar.vue
packages/kotti-ui/source/kotti-button-group/KtButtonGroup.vue
packages/kotti-ui/source/kotti-button/KtButton.vue
packages/kotti-ui/source/kotti-drawer/KtDrawer.vue
packages/kotti-ui/source/kotti-dropdown-button/KtDropdownButton.vue
packages/kotti-ui/source/kotti-filters/components/FilterActions.vue
packages/kotti-ui/source/kotti-filters/components/FilterList.vue
packages/kotti-ui/source/kotti-filters/components/FilterRow.vue
packages/kotti-ui/source/kotti-filters/components/FilterSearch.vue
packages/kotti-ui/source/kotti-input/KtInput.vue
packages/kotti-ui/source/kotti-modal/KtModal.vue
packages/kotti-ui/source/kotti-pagination/KtPagination.vue
packages/kotti-ui/source/kotti-popover/KtPopover.vue
packages/kotti-ui/source/kotti-popover/KtPopoverItem.vue
packages/kotti-ui/source/kotti-style/_cards.scss
packages/kotti-ui/source/kotti-style/_codes.scss
packages/kotti-ui/source/kotti-style/_comments.scss
packages/kotti-ui/source/kotti-style/_loadings.scss
packages/kotti-ui/source/kotti-style/_tables.scss
packages/kotti-ui/source/kotti-style/_typography.scss
packages/kotti-ui/source/kotti-style/_variables.scss
packages/kotti-ui/source/kotti-style/_workspace.scss
packages/kotti-ui/source/kotti-style/forms/_base.scss
packages/kotti-ui/source/kotti-style/forms/_input.scss
packages/kotti-ui/source/kotti-style/forms/_label.scss
packages/kotti-ui/source/kotti-style/spacing.css
packages/kotti-ui/source/kotti-style/utilities/_position.scss

This branch is rebased on top of #496.

Use CSS Custom Properties for Unit over Deprecated SCSS Variables

---

.github/workflows/rebase.yml

In theory, one simply has to comment `/rebase` to rebase a PR.

dx(github-actions): Add Rebase Action via /rebase

---

packages/documentation/components/ComponentInfo.vue

Rebased on top of #505, and #506

add-zod(3): Improve Documentation Rendering for Functions

---

packages/kotti-ui/source/kotti-banner/KtBanner.vue
packages/kotti-ui/source/kotti-breadcrumb/KtBreadcrumb.vue
packages/kotti-ui/source/kotti-button/KtButton.vue
packages/kotti-ui/source/kotti-field/constants.ts
packages/kotti-ui/source/kotti-filters/components/ButtonLink.vue
packages/kotti-ui/source/kotti-heading/KtHeading.vue
packages/kotti-ui/source/kotti-popover/KtPopover.vue
packages/kotti-ui/source/validators.ts
packages/yoco/package.json
packages/yoco/source/index.ts
packages/yoco/source/schema.ts
packages/yoco/source/validator.ts
yarn.lock

Rebased on top of #505, #506, and #507

add-zod(4): Move isYocoIcon to @3yourmind/yoco, Add yocoSchema

---

packages/kotti-ui/source/kotti-inline-edit/KtInlineEdit.vue

chore(KtInlineEdit): Remove Removed shadow Prop

---

packages/kotti-ui/source/make-props.test.ts
packages/kotti-ui/source/make-props.ts

Thought I needed this, didn’t end-up needing it. However, still good to have.

feature(makeProps): Add Support for z.date()

---

packages/kotti-ui/source/kotti-comment/KtCommentInput.vue

refactor(KtComment): Convert divClass to Computed

---

packages/documentation/components/NavBar.vue
packages/documentation/pages/examples/layouts.vue
packages/documentation/pages/usage/layouts/navbar.vue
packages/kotti-ui/source/kotti-navbar/components/NavbarMenu.vue
packages/kotti-ui/source/kotti-navbar/types.ts

Tries to solve the same problem as #473 but in a more controlled way.

KtNavbar: Add Support for Custom Link Components

---

packages/documentation/pages/examples/layouts.vue
packages/kotti-ui/source/kotti-user-menu/KtUserMenu.vue
packages/kotti-ui/source/kotti-user-menu/index.ts
packages/kotti-ui/source/kotti-user-menu/types.ts

Analogous to what was already done for Navbar

feat(KtUserMenu): make link component in KtUserMenu injectible

---

packages/kotti-ui/source/types/kotti.ts

This was forgotten for some reason

chore(KtUserMenu): add KottiUserMenu namepsace to exported types

---

packages/documentation/pages/usage/components/line.vue
packages/kotti-ui/source/kotti-line/KtLine.vue
packages/kotti-ui/source/kotti-line/types.ts

feat(#439): add interactivity and position to KtLine

---

packages/kotti-ui/source/kotti-comment/KtComment.vue
packages/kotti-ui/source/kotti-comment/KtCommentInput.vue
packages/kotti-ui/source/kotti-comment/index.ts
packages/kotti-ui/source/kotti-comment/types.ts
packages/kotti-ui/source/kotti-comment/utilities.ts
packages/kotti-ui/source/types/kotti.ts

Refactor kt comment: zod

---

packages/kotti-ui/source/kotti-comment/KtCommentInput.vue

Refactor kt comment topic/composition api comment input

---

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue

while the user is typing (field still in focus), we don't want to
..update the displayed value unless the user typed a numerically-different
..value
> e.g. if the user types 0.01 then removes the 1 at the end
> we want to still show 0.0 on the field until it is blurred
To achieve this, we maintain the history of the internalString each time
..the input changes (`@input`), and we reset this previous value
..on blur, or when the logical value is different
Refactors:
- remove redudant `truncatedNumber` variable
> we probably needed the toNumber(toString) double-operation before Big.js
> to compare small values or something
> this is now purely redundant
- minor stylistic refactor of functions into arrow functions
Co-Authored-By: Florian Wendelborn …

fix(KtFieldNumber): maintain history of displayed string

---

packages/documentation/pages/usage/components/form-fields.vue
packages/kotti-ui/source/index.ts
packages/kotti-ui/source/kotti-field-currency/KtFieldCurrency.vue
packages/kotti-ui/source/kotti-field-currency/constants.ts
packages/kotti-ui/source/kotti-field-currency/index.ts
packages/kotti-ui/source/kotti-field-currency/input-formatter.test.ts
packages/kotti-ui/source/kotti-field-currency/input-formatter.ts
packages/kotti-ui/source/kotti-field-currency/input-parser.test.ts
packages/kotti-ui/source/kotti-field-currency/input-parser.ts
packages/kotti-ui/source/kotti-field-currency/types.ts
packages/kotti-ui/source/kotti-field-currency/utilities.test.ts
packages/kotti-ui/source/kotti-field-currency/utilities.ts
packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue
packages/kotti-ui/source/kotti-field-number/constants.ts
packages/kotti-ui/source/kotti-field-number/utilities.ts
packages/kotti-ui/source/kotti-field/tests.ts
packages/kotti-ui/source/kotti-form-controller-list/tests.ts
packages/kotti-ui/source/kotti-form-controller-object/tests.ts
packages/kotti-ui/source/kotti-form/tests.ts
packages/kotti-ui/source/kotti-i18n/KtI18nContext.ts
packages/kotti-ui/source/kotti-i18n/hooks.ts
packages/kotti-ui/source/kotti-i18n/types.ts
packages/kotti-ui/source/types/decimal-separator.ts
packages/kotti-ui/source/types/kotti.ts
packages/kotti-ui/source/utilities.ts

feature(#249): Add KtFieldCurrency

---

packages/kotti-ui/source/kotti-field/hooks.ts
packages/kotti-ui/source/kotti-form-controller-list/components/FormControllerListItem.vue

Apparently this was intentionally done. No idea why.

fix(#617): Add Index to dataTest of KtFormControllerList

---

packages/documentation/pages/usage/components/popover.vue
packages/kotti-ui/source/kotti-comment/components/CommentActionsOptions.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue
packages/kotti-ui/source/kotti-field-date/hooks.ts
packages/kotti-ui/source/kotti-field-date/styles.scss
packages/kotti-ui/source/kotti-field-select/hooks/use-select-tippy.ts
packages/kotti-ui/source/kotti-field/KtField.vue
packages/kotti-ui/source/kotti-field/mixins.scss
packages/kotti-ui/source/kotti-popover/KtPopover.vue
packages/kotti-ui/source/kotti-popover/constants.ts
packages/kotti-ui/source/kotti-popover/types.ts

remove the clickBehavior prop from KtPopover and change the internal implementation

Fix click behavior on kt-popover

---

packages/yoco/package.json
yarn.lock

fix(zod): fix zod as a sub-dependency of yoco

---

packages/kotti-ui/source/kotti-field-toggle/components/ToggleBox.vue

See Ticket #657 for reference and how to (not any more) reproduce

fix(657): tell flex not to shrink its toggle

---

packages/documentation/components/NavBar.vue

fix(662): make sections reactive by wrapping it into computed

---

packages/documentation/pages/usage/components/breadcrumb.vue
packages/kotti-ui/source/kotti-breadcrumb/KtBreadcrumb.vue
packages/kotti-ui/source/kotti-breadcrumb/types.ts

feature(#660): make active step with color text-01 in KtBreadcrumbs

---

packages/kotti-ui/source/kotti-field-password/types.ts

fix(KtFieldPassword): typo

---

packages/documentation/pages/usage/components/form-fields.vue

Add configurable dataTest prop to form fields documentation page

Feat(KtField*): Add configurable dataTest prop to form fields documentation page

---

packages/kotti-ui/source/kotti-field-toggle/components/ToggleBox.vue

change color of checkbox on hover
remove dead focus-within class
remove argument of toggle-colors mixin related to stroke color of check
introduce argument for bg color to mixin

feat(KtFieldToggle): change color of checkbox bg

---

packages/documentation/data/menu.ts
packages/documentation/pages/usage/components/tag.vue
packages/kotti-ui/source/index.ts
packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue
packages/kotti-ui/source/kotti-tag/KtTag.vue
packages/kotti-ui/source/kotti-tag/index.ts
packages/kotti-ui/source/kotti-tag/types.ts
packages/kotti-ui/source/types/kotti.ts

- creates new component KtTag
- Uses KtTag in `GenericSelectField.vue`
- adds documentation page for KtTag

feat(KtTag): Create Chip Component for MultiSelects & Future Components

---

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue

fix(KtFieldNumber): fix in/decrement buttons click propagation

---

package.json
yarn.lock

Straight forward upgrade of lerna:
- [breaking changes in v5](https://github.com/lerna/lerna/releases/tag/v5.0.0) do not affect us 
- v6 is [non-breaking](https://blog.nrwl.io/lerna-reborn-whats-new-in-v6-10aec6e9091c#133c)

dep(lerna): bump to latest

---

packages/kotti-ui/source/kotti-button-group/KtButtonGroup.vue
packages/kotti-ui/source/kotti-button/KtButton.vue

due to the introduce of a div around each kt-button, the selectors .. have to be changed on kt-button

fix(KtButtonGroup): styles

---

packages/documentation/pages/usage/components/comment.vue
packages/kotti-ui/source/kotti-comment/KtComment.vue
packages/kotti-ui/source/kotti-comment/KtCommentInput.vue
packages/kotti-ui/source/kotti-comment/components/CommentActions.vue
packages/kotti-ui/source/kotti-comment/components/CommentEntry.vue
packages/kotti-ui/source/kotti-comment/components/CommentHeader.vue
packages/kotti-ui/source/kotti-comment/components/CommentInlineEdit.vue
packages/kotti-ui/source/kotti-comment/components/CommentTextArea.vue
packages/kotti-ui/source/kotti-comment/hooks.ts
packages/kotti-ui/source/kotti-comment/types.ts
packages/kotti-ui/source/kotti-comment/utilities.ts
packages/kotti-ui/source/kotti-i18n/locales/de-DE.ts
packages/kotti-ui/source/kotti-i18n/locales/en-US.ts
packages/kotti-ui/source/kotti-i18n/locales/es-ES.ts
packages/kotti-ui/source/kotti-i18n/locales/fr-FR.ts
packages/kotti-ui/source/kotti-i18n/locales/ja-JP.ts

Refact CommentInlineEdit.vue and KtCommentInput.vue
- Add isInternal and allowInternal flags
- Refact comment docs

refact(kt-comment): Refact CommentInlineEdit and KtCommentInput

---

packages/kotti-ui/package.json

Bump Yoco version to 2.4.4 in Kotti-ui

chore(yoco): bump to version 2.4.4

---

packages/documentation/pages/usage/components/comment.vue
packages/kotti-ui/source/kotti-comment/KtComment.vue
packages/kotti-ui/source/kotti-comment/KtCommentInput.vue
packages/kotti-ui/source/kotti-comment/components/CommentActions.vue
packages/kotti-ui/source/kotti-comment/components/CommentEntry.vue
packages/kotti-ui/source/kotti-comment/components/CommentInlineEdit.vue
packages/kotti-ui/source/kotti-comment/components/CommentTextArea.vue
packages/kotti-ui/source/kotti-comment/types.ts

Add `data-test` support to `KtComment`

feat(kt-comment): add data-test support

---

packages/documentation/pages/usage/components/comment.vue
packages/kotti-ui/source/kotti-comment/components/CommentTextArea.vue
packages/kotti-ui/source/kotti-comment/types.ts
packages/kotti-ui/source/kotti-i18n/locales/de-DE.ts
packages/kotti-ui/source/kotti-i18n/locales/en-US.ts
packages/kotti-ui/source/kotti-i18n/locales/es-ES.ts
packages/kotti-ui/source/kotti-i18n/locales/fr-FR.ts
packages/kotti-ui/source/kotti-i18n/locales/ja-JP.ts

KtComment: update toggle internal button icon and helpText
Update docs: add settings options for language, allowInternal, placeholder, tabIndex, dataTest

KtComment: update toggle internal button icon and helpText

---

packages/kotti-ui/source/kotti-style/_tables.scss

refact(kt-table): remove margin

---

packages/kotti-ui/source/kotti-field-file-upload/types.ts

refact Value types
- move common code to Shared
- expose specific types for newly selected files and pre-uploaded files for better usability

refact(kt-field-file-upload): refact Value types

---

packages/documentation/pages/usage/components/form-fields.vue
packages/documentation/pages/usage/components/form.vue
packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue

Emit blur when the focus is out of the whole KtFieldNumber (input + 2 buttons)

feat(#777): emit blur from KtFieldNumber

---

packages/kotti-ui/source/kotti-style/_tables.scss
packages/kotti-ui/source/kotti-table/KtTable.vue
packages/kotti-ui/source/kotti-table/style/form-checkbox.scss

Refact selectable checkbox styles
- Merge styles from KtTable.vue and _tables.scss
- Introduce styles/form-checkbox.scss

chore(kt-table): refact selectable checkbox styles

---

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue

Remove unused kt-field-number__middle__input--is-disabled style as the disabled styles are applied in KtField

chore(kt-field-number): remove unused disabled style

---

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue

Fix https://github.com/3YOURMIND/kotti/issues/772

fix(KtFieldNumber): when any of the buttons is disabled "cursor: not-allowed" is applied

---

packages/kotti-ui/source/kotti-avatar/KtAvatar.vue

Remove slots.content() call outside render() scope in setup

fix(kt-avatar): fix slots.content call outside render scope

---

packages/kotti-ui/source/kotti-field-select/components/Options.vue
packages/kotti-ui/source/kotti-field-select/types.ts

Support data test in KtField[Single | Multiple]Select[Remote] actions array items.

feat(kt-field-select): add data test to actions

---

packages/kotti-ui/source/kotti-field-inline-edit/components/ConfirmButton.vue

`data-test` instead of `datatest`

fix(KtFieldInlineEdit): confirm button data-test prop

---

packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUpload.vue
packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUploadRemote.vue
packages/kotti-ui/source/kotti-field-file-upload/styles.scss

Fix component width not filling its container's width in KtField

fix(kt-field-file-upload): fix component width

---

packages/documentation/pages/usage/components/filters.vue
packages/kotti-ui/source/constants.ts
packages/kotti-ui/source/kotti-filters/components/FilterRow.vue
packages/kotti-ui/source/kotti-filters/types.ts

Add support for shortcuts, minimum date, maximum date in DateRange filters.

feat(kt-filters): add date range shortcuts support

---

packages/kotti-ui/source/kotti-field-toggle/components/ToggleBox.vue
packages/kotti-ui/source/kotti-field-toggle/components/ToggleSwitch.vue

kt-field-toggle__inner changed to kt-field-toggle-inner

fix(KtFieldToggle): classes changed in #706

---

packages/kotti-ui/source/kotti-field-radio-group/KtFieldRadioGroup.vue
packages/kotti-ui/source/kotti-field-toggle/KtFieldToggleGroup.vue

..within kt-field-input-container-wrapper

fix(KtFieldRadio/ToggleGroup): allow growth/shrinkage

---

packages/kotti-ui/source/kotti-field-inline-edit/KtFieldInlineEdit.vue
packages/kotti-ui/source/kotti-field-inline-edit/components/EditIcon.vue

Fix wrong color for edit icon color when field is disabled

fix(kt-field-inline-edit): add disabled color for edit icon

---

packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue

Add missing data-test to KtField[DateRange|DateTime|DateTimeRange]

fix(kt-field-dates): add missing data-test to KtFieldDates

---

packages/kotti-ui/source/kotti-field/KtField.vue
packages/kotti-ui/source/kotti-field/types.ts

Add isLoadingValue prop to show loading state only on the input area of the field

feat(KtField): scope the isLoading skeleton to the input only

---

packages/kotti-ui/source/kotti-comment/components/CommentTextArea.vue
packages/kotti-ui/source/kotti-comment/utilities.ts
packages/kotti-ui/source/kotti-field-inline-edit/KtFieldInlineEdit.vue
packages/kotti-ui/source/kotti-field-inline-edit/types.ts
packages/kotti-ui/source/kotti-field-inline-edit/utils.ts
packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue
packages/kotti-ui/source/utilities.ts

- refact(kotti-ui/utils): move isEventTarget to root of kotti-ui with relevant changes
- fix(ktFieldInlineEdit): type typo on ComponentRef

Tech kotti UI utils refact is event target

---

packages/documentation/pages/usage/components/form-fields.vue
packages/kotti-ui/source/kotti-field-text-area/KtFieldTextArea.vue
packages/kotti-ui/source/kotti-field-text-area/types.ts

- if autoSize is true, the textarea get resized unless the height is above the maxHeight property

feature(857): add a property autoSize and maxHeight for KtFieldTextArea

---

packages/kotti-ui/source/kotti-comment/KtCommentInput.vue
packages/kotti-ui/source/kotti-comment/components/CommentInlineEdit.vue
packages/kotti-ui/source/kotti-field-file-upload/components/DropArea.vue
packages/kotti-ui/source/kotti-field-file-upload/components/TakePhoto/TakePhoto.vue

Recommended by vue starting in 2.7
Co-Authored-By: Carol Soliman <17387510+carsoli@users.noreply.github.com>

refactor(kotti): Avoid Using Variables With $ or _ in the Template

---

packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelect.vue
packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelectRemote.vue
packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelect.vue
packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelectRemote.vue

..instead of manually exposing `props` object

refactor(KtField*Select*): Use $props on Template

---

packages/kotti-ui/source/kotti-i18n/locales/de-DE.ts
packages/kotti-ui/source/kotti-i18n/locales/en-US.ts
packages/kotti-ui/source/kotti-i18n/locales/es-ES.ts
packages/kotti-ui/source/kotti-i18n/locales/fr-FR.ts
packages/kotti-ui/source/kotti-i18n/locales/ja-JP.ts
packages/kotti-ui/source/kotti-navbar/components/NavbarMenu.vue

refactor(KtTranslation): replace namespace with module

---

README.md
packages/kotti-ui/package.json
packages/kotti-ui/vite.config.ts
packages/yoco/README.md

- remove dead code from vite.config
- fix README to point to correct paths of style.css

fix(kotti-ui): path to style.css

---

packages/kotti-ui/source/kotti-heading/KtHeading.vue

Fixed unmatched label after a chrome warning.

fix(KtHeading): BREAKING replace <label> with <span>, also rework styles

---

internals/scripts/source/publish.ts
packages/yoco/package.json

uses the new build system and also test auto publish via pipeline

version(yoco@2.5.0): add support for esm

---

packages/kotti-ui/source/kotti-user-menu/KtUserMenu.vue

fix(KtUserMenu): tell avatar to not shrink

---

package.json
yarn.lock

Bump @babel/preset-env to v7.24.7

dependencies(babel-preset-env): bump to v7.24.7

---

packages/documentation/pages/usage/components/table-legacy.vue
packages/kotti-ui/source/kotti-table-legacy/components/TableHeader.vue
packages/kotti-ui/source/kotti-table-legacy/components/TableRow.ts
packages/kotti-ui/source/kotti-table-legacy/style/form-checkbox.scss

Refact row selection and selection checkboxes styles to fix row selection reactivity not working.
Also improve KtTableLegacy documentation.

fix(kt-table-legacy): fix row selection reactivity not working

---

packages/kotti-ui/package.json

- Add autoComplete prop to KtFields
- Bug fixes in KtTableLegacy

version(kotti-ui@7.1.0):  Improvements in KtFields

---

packages/documentation/data/menu.ts
packages/documentation/pages/usage/components/field-inline-edit.vue
packages/documentation/pages/usage/components/file-upload.vue
packages/kotti-ui/package.json
packages/kotti-ui/source/kotti-field-file-upload/components/ProgressBar.vue
packages/kotti-ui/source/kotti-field-file-upload/components/TakePhoto/Capture.vue
packages/kotti-ui/source/kotti-field-file-upload/components/TakePhoto/Error.vue
packages/kotti-ui/source/kotti-field-file-upload/components/TakePhoto/Review.vue
packages/kotti-ui/source/kotti-field-file-upload/components/TakePhoto/TakePhoto.vue
packages/kotti-ui/source/kotti-field-file-upload/types.ts
packages/kotti-ui/source/kotti-file-upload/KtFileUpload.vue
packages/kotti-ui/source/kotti-file-upload/components/UploadedFileItem.vue
packages/kotti-ui/source/kotti-file-upload/types.ts

Also includes some bug fixes and clean-ups

chore(KtFileUpload): add documentation page for KtFileUpload

---

.gitignore
README.md
crowdin.yml
packages/kotti-ui/source/kotti-i18n/locales/de-DE.ts
packages/kotti-ui/source/kotti-i18n/locales/en-US.ts
packages/kotti-ui/source/kotti-i18n/locales/es-ES.ts
packages/kotti-ui/source/kotti-i18n/locales/fr-FR.ts
packages/kotti-ui/source/kotti-i18n/locales/ja-JP.ts
packages/kotti-ui/source/locales/input.json

- add config file
- cleanup spanish translations
- fix some keys sorting

chore(kotti-i18n): add crowdin translations

---

packages/kotti-ui/source/kotti-pagination/KtPagination.vue

this was introduced by making pagination 1-indexed

fix(KtPagination): disable back button on first page

---

packages/documentation/pages/usage/components/form-fields.vue
packages/kotti-ui/source/kotti-field-currency/KtFieldCurrency.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue
packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue
packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUpload.vue
packages/kotti-ui/source/kotti-field-file-upload/components/DropArea.vue
packages/kotti-ui/source/kotti-field-password/KtFieldPassword.vue
packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue
packages/kotti-ui/source/kotti-field-select/hooks/use-select-tippy.ts
packages/kotti-ui/source/kotti-field-text-area/KtFieldTextArea.vue
packages/kotti-ui/source/kotti-field-text/KtFieldText.vue

Scope:
- KtFieldCurrency
- KtFieldDate
- KtFieldDateRange
- KtFieldDateTime
- KtFieldDateTimeRange
- KtFieldFileUpload
- KtFieldMultiSelect
- KtFieldMultiSelectRemote
- KtFieldNumber
- KtFieldPassword
- KtFieldSingleSelect
- KtFieldSingleSelectRemote
- KtFieldText
- KtFieldTextArea

feat(kt-form-fields): add blur event support to form fields

---

packages/kotti-ui/source/kotti-field-radio-group/KtFieldRadioGroup.vue
packages/kotti-ui/source/kotti-style/tokens.css
packages/kotti-ui/source/shared-components/toggle-inner/ToggleBox.vue
packages/kotti-ui/source/shared-components/toggle-inner/ToggleInner.vue
packages/kotti-ui/source/shared-components/toggle-inner/ToggleSwitch.vue
packages/kotti-ui/tokens/colors.js

- Figma for checkboxes/toggles: https://www.figma.com/design/0yFVivSWXgFf2ddEF92zkf/Kotti-Design-System?node-id=6815-8673&node-type=section&t=xaKVnXiFtzcOEdF0-0
- Figma for radios: https://www.figma.com/design/0yFVivSWXgFf2ddEF92zkf/Kotti-Design-System?node-id=6815-8672&node-type=section&t=xaKVnXiFtzcOEdF0-0
- Figma for switches: https://www.figma.com/design/0yFVivSWXgFf2ddEF92zkf/Kotti-Design-System?node-id=6815-8671&node-type=section&t=xaKVnXiFtzcOEdF0-0

Update styles of toggles, switches, and radios

---

packages/documentation/pages/usage/components/popover.vue
packages/kotti-ui/source/kotti-popover/KtPopover.vue

chore(KtPopover): remove obsolete CSS hack for tippy popper
