packages/kotti-table/src/TableBody.js, packages/kotti-table/src/constants.js, packages/kotti-table/src/logic/sort.js
- fixed loading state leaving already loaded columns visible
- added support for passing 1 or -1 in the sortedColumn prop as a possible sortOrder value
=> some fixes while using KtTable with remote sort

packages/kotti-comment/src/Comment.vue, packages/kotti-comment/src/CommentReply.vue
We need to handle id as String, because we are using UUID as id and UUID are Strings.
=> fix: id can now be Number or String

packages/kotti-style/_comments.scss
Just add word break on comments.
=> fix: add word-break to comment message and comment reply message

docs/pages/patterns/comments.vue, packages/index.js, packages/kotti-comment/index.js, packages/kotti-comment/src/Comment.vue, packages/kotti-comment/src/CommentReply.vue
CommentReply accepts HTML but Comment didn't. Added that and a parser option in order to parse new lines tags
also added docs and allows named exports in main kotti in order to be able to get the KtComment.defaultParser
but then I also realized we could generally make it such that KtComment always escapes and then runs the user passed parser (so that users don't forget and shoot themselves in the foot)
=> fix comment component accepting html and opt in parsing

packages/kotti-table/src/TableHeader.vue
Fix hyphens issue on table controls on firefox.
=> fix: fix table control on firefox

docs/pages/patterns/inline-edit.vue, packages/kotti-inline-edit/src/InlineEdit.vue
I thought just allowing the parser would have been enough but it seems that the inlineEdit component used input which wouldn't allow users to have multiple lines
Added a multiline flag that would switch the input field to a text area and default parser to newLineParser.
I ported the component into Yoda in order to test it in components so it's not urgent to publish a new version after this merges
=> suport multiline flag for inlineEdit component

docs/components/Navbar.vue, docs/pages/examples/layouts.vue, docs/pages/patterns/navbar.vue, packages/kotti-navbar/src/KtNavbar.vue, packages/kotti-navbar/src/KtNavbarLogo.vue, packages/kotti-navbar/src/KtNavbarMenu.vue, packages/kotti-navbar/src/KtNavbarNotification.vue, packages/kotti-navbar/src/KtNavbarQuickLink.vue, packages/kotti-user-menu/src/UserMenu.vue
The API changes will change when next release, you don't need to specify the borderColor anymore.
**Prvider name changed from `KtNavbarTheme` to `KtTheme`**
Default Theme Provider
```js
provide() {
return {
KtTheme: {
navbarBackgroundColor: '#122C56',
navbarTextColor: 'rgba(255,255,255,.54)',
navbarTextActiveColor: 'rgba(255,255,255, 1)',
logoUrl: LogoSvg,
logoHeight: '40px',
},
}
},
```
=> feature: change KtNavbarTheme to KtTheme #63

packages/index.js
Previously, `toggle(false)` would `toggle(true)`.
=> fix(kotti): Make `toggle(false)` work

docs/pages/components/tables.vue, packages/kotti-table/index.js, packages/kotti-table/src/Table.vue, packages/kotti-table/src/TableColumn.js, packages/kotti-table/src/TableConsumer.js, packages/kotti-table/src/TableHeader.vue, packages/kotti-table/src/TableProvider.js, packages/kotti-table/src/TableRow.js, packages/kotti-table/src/TableRowCell.js, packages/kotti-table/src/constants.js, packages/kotti-table/src/logic/column.js, packages/kotti-table/src/logic/filter.js, packages/kotti-table/src/logic/hide.js, packages/kotti-table/src/logic/order.js, packages/kotti-table/src/logic/row.js, packages/kotti-table/src/logic/select.js, packages/kotti-table/src/logic/sort.js, packages/kotti-table/src/logic/store.js, packages/kotti-table/src/mixins.js
Fix Column order swapping instead of setting ordering in correct spot
Fix Reusable columns appearing our of order due to none unique keys
Fix #73
Fix clicking on actions triggering rowClick
Added KtConsumer to be used with KtProvider instead of Mixin solution for clearer DX
Added KtProvider to the docs
=> updated KtTable

packages/kotti-input/src/Input.vue
Initially, no for attribute was added if the `labelFor` props was not used.
We are now using that props if defined and the component `uid` will help generate an unique for/id pair.
=> feature: Add default for attributes for label

docs/pages/components/popovers.vue, packages/kotti-popover/src/Popover.vue
What has been done?
* fixed the scenario where a dropdown selection would auto close the Popover component
How to test?
* This scenario can be tested in the documentation pages related to Popover.
=> bugfix(KtPopover): fix auto close of Popover on nested Dropdown selection

.gitignore, packages/kotti-input-number/src/InputNumber.vue
The number input component did not function correctly in ie11. The bug was the use of stepUp - an html input method that does not exist in IE11.
=> chore(fix number input not working in IE11)

docs/pages/components/radios.vue, docs/pages/components/selects.vue, packages/kotti-radio-group/src/RadioGroup.vue, packages/kotti-single-select/src/SingleSelect.vue, packages/kotti-style/forms/_input.scss
Radio and Select didn't pass the required prop right away but rather worked around it
radiogroup was a wrapper with no actual input html on the parent component >
(now it has a hidden input that becomes invalid and uses the native required attribute)
singleselect had a readonly attribute so it couldn't be invalidated when it was readonly >
now it mimics the readonly attribute but can be invalidated
-fixed singleselect to show all options (not just filtered) when the input field is out of focus then selected again
-fixed a null invocation error
issue#111
=> fix(required prop works natively now and not just using css)

packages/kotti-accordion/KtAccordion.vue, packages/kotti-banner/src/Banner.vue, packages/kotti-input-number/src/InputNumber.vue
made `expandable` return boolean when no slot="expand" exists
if no actionText is provided and since it defaults to empty string, button doesn't show at all (v-if)
#126
=> fix(issue#126): removed empty default actionButton in KtBanner

packages/kotti-single-select/src/SingleSelect.vue
I don’t see any benefit of allowing an user to search for values that said user can’t even see. This caused various weird search results in AMPI’s filter functionality.
=> fix(KtSingleSelect): Searching for Internal Values

packages/kotti-input-number/src/InputNumber.vue
This PR fixes some buggy behaviour in the kt-number-input component. The bug was that "min" was not being factored in - for either the css or for the purposes of disallowing decrementing below the min threshold.
=> resolved min and max not being factored in factored in

packages/kotti-input-number/src/InputNumber.vue
This PR fixes wrong color in the input when disabled (shouldn't be there at all), and makes it so that if the component is created disabled, increment and decrement are disabled as well.
=> fixed disabled color and added disabled to create hook

docs/assets/css/main.scss, docs/pages/components/inputnumber.vue, packages/kotti-button/src/button.vue, packages/kotti-input-number/src/InputNumber.vue
Bug fixes:
1) we can input numbers that are invalid (>max or <min) --> they show an invalid style and store the new currentValue locally (in the component) but don't emit the faulty input (which is ok)
However, this non-emission does not allow for the faulty value to be recognized by a parent component so we allow submission if we use this field in a form (with the correct value since it's not emitted with an @input event) BUT it's confusing for the user to see an invalid styling, and be able to submit, then see that the actual saved value is not the FAULTY one they "typed" in 
2) initially, we didn't disable increment and decrement buttons and so if initially the component had a value == max or value == min, (2/2, for example) they could go up by one increment, before the buttons are …
=> fix(#151): KtInputNumber Increment Issues & Refactor

packages/kotti-input-number/src/InputNumber.vue
regex didn't account for non-dot decimal separators
=> fix(161): broken regex for decimal separators

docs/pages/components/inputnumber.vue, packages/kotti-input-number/src/InputNumber.vue
if value is null, increment and decrement buttons are still enabled
if either buttons are pressed, we set internal currentValue to "0"
thus setting internal currentValueNumber to 0
then component behaves as normal
Notes: 
1) incentive for this is in issue description
2) FT can be done in docs (there is a null example) but also test other examples
issue #167
=> enhance(#167): different handling of null values in KtInputNumber

packages/kotti-input-number/src/InputNumber.vue
1. made `this.value` the source of truth
2. rename: `currentValue` was the `internalStringValue` --> now it's clearer
3. treat DECIMAL_SEPARATOR (e.g. `"."`) as null
4. added `isStepMultiple` check as validity check, which mirrors the behavior of a native number-typed input in html 
5. updated `isInRange` to include offset, to differentiate a `null` value, and a value that became `0` when the offset was passed as part of the value
6. currentValueNumber is now redundant because this.value is the source of truth
7. only update internal state in the watcher for value, thus, relying on `@input` and only emit 'input' when we have VALID user-input or empty strings (treated as null)
=> #176 make KtInputNumber controlled

package.json
The `postPublish` hook should now re-tag instead of failing when the tag already exists (e.g. by someone using `npm version` instead of incrementing a number)
=> fix(#165): Adjust postPublish Hook to Re-Tag

packages/kotti-button/src/button.vue
According to the HTML specs, every `<button>` element is implicitly `type="submit"`. This can cause forms to submit by clicking arbitrary buttons. This might cause it to click on a delete button when the user hits enter.
=> fix(KtButton): Set Type Button Explicilty to Prevent Implicit Type Submit

packages/kotti-input-number/src/InputNumber.vue
apparently my upstream revived itself
isStepMultiple didn't guard against null values now that we allow them, and that results is arbitrary
=> fix(#176): added guard against null value in isStepMultiple

packages/kotti-table/src/Table.vue, packages/kotti-table/src/logic/column.js, packages/kotti-table/src/logic/hide.js, packages/kotti-table/src/logic/order.js, packages/kotti-table/src/logic/sort.js
We found some more unused functions in the KtTable.
=> Refactor(KtTable): Remove Dead Code of getColumnsArray

package.json, packages/kotti-table/src/logic/order.js
result: dragging columns to the first index is rendered correctly
how to test: 
verify that a draggable column table with column order caching saves the order correctly if a     column is dragged to the first order
=> safer order checking with typeof equals number for order 0 (KtTable: column ordering)

package.json, packages/documentation/package.json, packages/kotti-ui/package.json, packages/test-app/package.json
the files to check differ according to each package, and directories like node_modules and dist should not be checked
otherwise, output dist contains css that's checked
=> fix(scripts): stylelint scripts moved to each package separately

packages/kotti-ui/source/kotti-col/index.ts, packages/kotti-ui/source/kotti-row/constants.ts, packages/kotti-ui/source/kotti-row/index.ts, packages/kotti-ui/source/kotti-row/types.ts
introduced KT_ROW_CONTEXT for proper provide/inject
(added relevant types and constants)
injected CONTEXT in KtCol
bug-fix: most props defaulted to null, which matched the `typeof prop === 'object'` which threw an error
cleanup: restricted all media-query props to be of type number only and we double-checked all usages
simplified the classes computation accordingly
TLDR; fixed bug and simplified KtCol, and refactored types, and used proper context provision
Co-authored-by: Florian Wendelborn <1133858+FlorianWendelborn@users.noreply.github.com>
=> fix/refact(KtCol): refactoring broke KtCol

packages/kotti-ui/rollup.config.js
Previously, element-ui was treated as external, but the element-ui/locale/… folder was treated as internal as it didn’t match in the external array.
The regex now matches anything that mentions element-ui instead.
Basically, the locale.js file has a local variable lang that gets overwritten when setting the locale. However, the code for setting the locale was inlined by rollup while the code reading the locale (element-ui itself) was treated as external.
This means that the file itself was copied twice, meaning that the variables were also duplicated. Element-UI’s locale kept the chinese version while Kotti’s copied version of element-ui’s locale was set to english.
---
Element UI tried to read from: `node_modules/element-ui/lib/locale/index.js`
We wrote to `dist/esm/index.js`’s local …
=> fix(#263): Exclude Element-UI Entirely

packages/documentation/pages/components/buttons.vue, packages/kotti-ui/source/kotti-button/KtButton.vue
This PR tackles two things:
- A `isBlock` modifier for the button to act like a block element and use all the width available
- A `isMultiline` modifier so it can handle long text on buttons
The reason I used a modifier instead of having the button just handle it is that using `line-height` is less reliable than `height` for button sizing.
Also the handling of icons needs to be different and we rather "control" which are meant to multiline or not.
=> Multiline and block buttons

packages/kotti-ui/source/kotti-button/KtButton.vue
This highen up the specificity of the selector to fix random order CSS.
=> fix: up the selector specificity for multiline and block buttons

packages/kotti-ui/source/next/kotti-field-select/hooks.ts
when using the selects with a field that has keywords like "address" in its label/parent wrapper, chrome recognizes the input field as autofillable and shows autofill suggestions as per saved autofill data in chrome://settings
to counter-act this, since `autocomplete=off` doesn't work in recent versions of chrome to disable autofill suggestions, we change the input type to search instead of text, thus excluding the field from the fillable criteria
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-expectation-mantle
=> fix(300): counter-act chrome autocomplete attribute disregard

packages/kotti-ui/source/next/kotti-field-date/KtFieldDate.vue, packages/kotti-ui/source/next/kotti-field-date/KtFieldDateRange.vue, packages/kotti-ui/source/next/kotti-field-date/KtFieldDateTime.vue, packages/kotti-ui/source/next/kotti-field-date/KtFieldDateTimeRange.vue, packages/kotti-ui/source/next/kotti-field-date/hooks.ts, packages/kotti-ui/source/next/kotti-field/KtField.vue
`refs` shouldn't be extracted from SetupContext (it still works, though)
there was a type error that `refs` is undefined on `SetupContext`
recommended method in docs https://composition-api.vuejs.org/api.html#template-refs
serve docs with `yarn run --cwd packages/documentation serve`
on the `form-fields` page under `Components`
test that the tool-tip classes goes above and below according to the space available above it on `form-fields` page
=> Use refs as recommended on kt field

packages/documentation/pages/components/form-fields.vue, packages/documentation/pages/components/form.vue, packages/kotti-ui/source/next/kotti-field-date/hooks.ts, packages/kotti-ui/source/next/kotti-field-radio-group/KtFieldRadioGroup.vue, packages/kotti-ui/source/next/kotti-field-text-area/KtFieldTextArea.vue, packages/kotti-ui/source/next/kotti-field-toggle/components/ToggleBox.vue, packages/kotti-ui/source/next/kotti-field-toggle/components/ToggleSwitch.vue, packages/kotti-ui/source/next/kotti-field/KtField.vue, packages/kotti-ui/source/next/kotti-field/hooks.ts, packages/kotti-ui/source/next/kotti-field/mixins.scss, packages/kotti-ui/source/next/kotti-field/tests.ts, packages/kotti-ui/source/next/kotti-field/types.ts, packages/kotti-ui/source/next/kotti-form/controllers/tests.ts, packages/kotti-ui/source/next/kotti-form/tests.ts, packages/kotti-ui/source/next/kotti-form/utilities.ts
Vetur can't eliminate a member of a Union type with a `null` value.
type X = { key1: null } | { key1: 'a', key2: string }
when checking for X.key1 === null and returning from a statement, we expect that key2 will always be defined
but Vetur couldn't recognise that the first type was eliminated by the check
fix: work-around: change key1 from `null` to another string; `empty`
refactor: tests/classes/usages that were affected by the Validation type change
Co-authored-by: Florian Wendelborn <1133858+FlorianWendelborn@users.noreply.github.com>
=> fix():`validationText` type in Vetur

packages/kotti-ui/source/next/kotti-field/KtField.vue
Validation.Result has type `Empty` which now has a type value `'empty'` and not `null`
accordingly, fixed `showValidation` to match the new values of `validationType` (we hide validation if the type is Empty)
follow-up to [!316](https://github.com/3YOURMIND/kotti/pull/316)
=> fix(): fix `ValidationType` check on KtField to match Empty validation

packages/kotti-ui/source/next/kotti-field/KtField.vue, packages/kotti-ui/source/next/kotti-field/types.ts, packages/kotti-ui/source/next/kotti-translation/locales/de-DE.ts, packages/kotti-ui/source/next/kotti-translation/locales/en-US.ts, packages/kotti-ui/source/next/kotti-translation/locales/es-ES.ts, packages/kotti-ui/source/next/kotti-translation/locales/fr-FR.ts, packages/kotti-ui/source/next/kotti-translation/locales/ja-JP.ts
- removed `requiredLabel` from translation context (breaking change)
- removed requiredLabel from UI (i.e. no longer show `(Required)` next to label of required fields
- show `*` instead ^
- make the asterix go red with validation when a field is required and empty
- add validation icon next to the error msg (Yoco.Icon.CIRCLE_CROSS for error messages, and Yoco.Icon.CIRCLE_CHECK for success messages and Yoco.Icon.CIRCLE_ATTENTION for warning messages)
---
1. `git pull --rebase`
2. `yarn run watch` should build and serve the docs
3. go to components/form-fields, change the field switch `isOptional` to be false (i.e. make field required)
4. then if the field is empty, the asterix should be red and there should be a custom error state (not the msg that the field is required)
5. type in the …
=> 312 change required ui for fields

packages/documentation/pages/examples/layouts.vue, packages/kotti-ui/source/kotti-navbar/KtNavbar.vue
This PR add:
- A way of theming the navbar differently, by overwriting the `primary` colors on `.kt-navbar`.
- Two navbar themes: `light` and `dark`
- A way of changing navbar theme in the navbar documentation
This PR removes:
- The `grayscale` theme, that is not used anymore (was used for SP)
To test: 
Run server and go to <http://localhost:3000/examples/layouts#>, or go to <http://localhost:3000/patterns/navbar> and click on "Open Example".
There is a select that allow us to select theme. 
Please ignore the notification area as it wasn't really supported on default theme.
=> More theming for navbar

packages/kotti-ui/source/next/kotti-field/KtField.vue
Don’t show label as loading if no label or helptext exist
Don’t include header if unnecessary to avoid additional margin-top
```vue
<KtFieldText
formKey="textValue"
isLoading
isOptional
/>
```
should load without having a loading label
```vue
<KtFieldText
formKey="textValue"
isOptional
/>
```
should no longer have a useless margin-top
=> fix(KtField*): Better Handling of Missing Labels

packages/kotti-ui/source/next/kotti-field-number/KtFieldNumber.vue
track cursor position before feeding the value back to the input field
via native DOM attributes/functions
setting the cursor position back once we settle on what the value is
Co-authored-by: Danie Beckstein <53575247+Daniel-Beckstein@users.noreply.github.com>
=> fix(#337): fix cursor position on KtFieldNumber

packages/documentation/pages/components/form-fields.vue, packages/kotti-ui/source/next/kotti-field-select/KtFieldMultiSelect.vue, packages/kotti-ui/source/next/kotti-field-select/KtFieldSingleSelect.vue, packages/kotti-ui/source/next/kotti-field-select/constants.ts, packages/kotti-ui/source/next/kotti-field-select/types.ts, packages/kotti-ui/source/next/kotti-field-toggle/KtFieldToggleGroup.vue, packages/kotti-ui/source/next/kotti-field-toggle/components/ToggleBox.vue, packages/kotti-ui/source/next/kotti-field-toggle/components/ToggleInner.vue, packages/kotti-ui/source/next/kotti-field-toggle/components/ToggleSwitch.vue, packages/kotti-ui/source/next/kotti-field-toggle/types.ts
Mostly used to improve the tooltips in `/service-panel/materials/1/price`:
=> feature(KtFieldToggleGroup): Support tooltip on options

packages/documentation/pages/components/form.vue, packages/kotti-ui/source/kotti-form/controllers/KtFormControllerList.vue, packages/kotti-ui/source/kotti-form/index.ts
added header/footer slots which expose almost the same scoped functions/props as the default slot (addBefore, addAfter, setValues, values)
use-cases are for the overall list vs having those utilities per element
Co-authored-by: Florian Wendelborn <1133858+FlorianWendelborn@users.noreply.github.com>
=> feat(): add footer/header slots to KtFormControllerList & enhance docs

packages/documentation/pages/components/popover.vue, packages/kotti-ui/source/index.ts, packages/kotti-ui/source/kotti-popover/KtPopover.vue, packages/kotti-ui/source/kotti-popover/KtPopoverIconTextItem.vue, packages/kotti-ui/source/kotti-popover/index.ts
Created component KtPopoverIconTextItem to handle buttons displayed as icons + text and permits disabled class on them.
Created fallback case in KtPopover that does a loop on prop "options" to display KtPopoverIconTextItems.
Added validator function in KtPopover to control prop options.
=> feature(#366): Implement Options in KtPopover

.gitignore, package.json, packages/yoco/.gitignore
prettier doesn't ignore gitignore and attempts to `--check` and `--write` directories like `dist/` of esm build, which obviously fails.
=> Fix prettier scripts

packages/kotti-ui/source/kotti-navbar/KtNavbar.vue, packages/kotti-ui/source/kotti-navbar/components/NavbarLogo.vue, packages/kotti-ui/source/kotti-navbar/components/NavbarMenu.vue
Closes #338
Hides the logo if the layout switches to mobile-like
Aligns icons in center when navbar is slim
Removes some dead code/css along the way
=> fix(#338): kt navbar logo

packages/kotti-ui/source/kotti-navbar/KtNavbar.vue, packages/kotti-ui/source/kotti-navbar/components/NavbarLogo.vue
* increases toggle button icon size dramatically
* improves click targets (especially for mobile — you can click outside the button and it still registers appropriately)
* refactors `NavbarLogo` to `@vue/composition-api`
* fixes mobile logo not emitting `click`
| Before | After |
|:--|:--|
| ![image](https://user-images.githubusercontent.com/1133858/112012148-3c81ed80-8b29-11eb-974e-c5784de6803d.png) | ![image](https://user-images.githubusercontent.com/1133858/112012058-283df080-8b29-11eb-9119-4dafce59f3a5.png) |
| ![image](https://user-images.githubusercontent.com/1133858/112012236-50c5ea80-8b29-11eb-9193-832132dd80b0.png) | ![image](https://user-images.githubusercontent.com/1133858/112012296-5d4a4300-8b29-11eb-874f-7d8cc0351d23.png) |
=> fix(KtNavbar): Better Click Targets & Icon Scaling

packages/kotti-ui/source/kotti-field-select/hooks.ts
to re-trigger width setting of popper
=> fix(#336): register `visible` on watchEffect

packages/documentation/pages/usage/components/form-fields.vue, packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelect.vue, packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelect.vue, packages/kotti-ui/source/kotti-field-select/constants.ts, packages/kotti-ui/source/kotti-field-select/styles.scss, packages/kotti-ui/source/kotti-field-select/types.ts
update KtFieldSingleSelect to have a create option
https://www.figma.com/file/2fayetfljWKphvid6wB2Dy/New-Kotti-Component-%3A-Form-%2F-Select-%2F-Open-with-Link?node-id=1%3A217
When a prop ```action``` is passed to KtFieldSingleSelect, a separator is added at the end of the select and a link is placed under the separator with a label.
=> Update single select to contain possibility of a create option

packages/kotti-ui/source/kotti-navbar/components/NavbarLogo.vue
For desktop, constrain the logo's width instead of height
=> Fix small logo

packages/kotti-ui/source/kotti-accordion/KtAccordion.vue
Designs: <https://www.figma.com/file/0yFVivSWXgFf2ddEF92zkf/Kotti-Design-System?node-id=173%3A2598>
Bonus :bug:fix: Clicking the Open/close icon in a "fully" clickable `KtAccordion` no longer toggles the accordion twice...
* ❌ misaligned icon
* ❌ small icon
* ❌ misaligned close button
* ❌ small close button
* ❌ double-border at the bottom
* ✅ centered icon
* ✅ properly-sized icon
* ✅ centered close button
* ✅ properly-sized close button
* ✅ normal border at the bottom
---
Try this PR for free for 7 days. No credit-card required!
=> fix(KtAccordion): Proper Centering & Border

packages/yoco/style.css
=> fix(#405): Prevent Hyphenation in Yoco Icons

packages/kotti-ui/source/kotti-button/KtButton.vue
| Browser | Before | After |
|:--|:--|:--|
| Firefox | ![image](https://user-images.githubusercontent.com/1133858/115923468-90605900-a47e-11eb-8b9e-87df59ee45c0.png) | ![image](https://user-images.githubusercontent.com/1133858/115923909-45931100-a47f-11eb-80da-c268615cb811.png) |
| Safari | ![image](https://user-images.githubusercontent.com/1133858/115923529-a706b000-a47e-11eb-8dc5-d27fb9c01639.png) | ![image](https://user-images.githubusercontent.com/1133858/115924136-9e62a980-a47f-11eb-9c6e-c5c5a51ddb90.png) |
| Chrome | ![image](https://user-images.githubusercontent.com/1133858/115923584-bdad0700-a47e-11eb-8b3d-9f43b55de577.png) | ![image](https://user-images.githubusercontent.com/1133858/115924065-812ddb00-a47f-11eb-8f0e-71d36c00df43.png) |
Safari doesn’t support the `:focus-visible` …
=> fix(#413): KtButton Explicit Focus Behavior

packages/kotti-ui/source/kotti-button/KtButton.vue
| Browser | Before | After |
|:--|:--|:--|
| Firefox | ![image](https://user-images.githubusercontent.com/1133858/115921721-2cd52c00-a47c-11eb-9192-f5917f732665.png) | ![image](https://user-images.githubusercontent.com/1133858/115922173-da483f80-a47c-11eb-8869-5ef7a50a62f7.png) |
| Safari | ![image](https://user-images.githubusercontent.com/1133858/115921753-3bbbde80-a47c-11eb-9097-0e9330d3b80c.png) | ![image](https://user-images.githubusercontent.com/1133858/115922352-14194600-a47d-11eb-8e91-55920d909def.png) |
| Chrome | ![image](https://user-images.githubusercontent.com/1133858/115921810-52facc00-a47c-11eb-9f57-5d19f9391fb5.png) | ![image](https://user-images.githubusercontent.com/1133858/115922286-fe0b8580-a47c-11eb-9aba-aea606dc7d7f.png) |
---
Closes #411
=> fix(#411): Specify Background Colors for Danger KtButton

packages/kotti-ui/package.json, yarn.lock
Finally gets rid of `node-sass` in [the implicit dependencies](https://github.com/thgh/rollup-plugin-scss/blob/e2a3f760c13ba473b6b83ff3adb20b385be9ea80/CHANGELOG.md). Thus, saving time when `yarn install`ing. From my testing, `yarn install` is now **70% faster**
```
~/C/@/kotti ❯❯❯ time yarn install
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > jsdom-global@3.0.2" has unmet peer dependency "jsdom@>=10.0.0".
warning " > sass-loader@9.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning " > @3yourmind/kotti-ui@3.0.0-alpha.26" has unmet peer dependency "@vue/composition-api@0.6.1".
warning " > @3yourmind/kotti-ui@3.0.0-alpha.26" has unmet peer dependency "core-js@*".
warning …
```
=> build(kotti-ui): Remove node-sass by Upgrading rollup-plugin-scss

.gitignore, packages/kotti-ui/package.json, packages/kotti-ui/rollup.config.js, yarn.lock
There’s now a bundle visualizer for rollup. Output is `packages/kotti-ui/report.(cjs|esm).html` right now.
```
~/C/@/kotti ❯❯❯ hyperfine "yarn workspace @3yourmind/kotti-ui run build:kotti:esm:visualizer" "yarn workspace @3yourmind/kotti-ui run build:kotti:esm" "yarn workspace @3yourmind/kotti-ui run build:kotti:cjs:visualizer" "yarn workspace @3yourmind/kotti-ui run build:kotti:cjs"
Benchmark #1: yarn workspace @3yourmind/kotti-ui run build:kotti:esm:visualizer
Time (mean ± σ):     21.472 s ±  0.581 s    [User: 28.460 s, System: 3.235 s]
Range (min … max):   20.821 s … 22.338 s    10 runs
Benchmark #2: yarn workspace @3yourmind/kotti-ui run build:kotti:esm
Time (mean ± σ):     19.918 s ±  0.311 s    [User: 26.965 s, System: 3.105 s]
Range (min … max):   19.477 s … 20.469 s    10 runs …
```
=> improvement(build): Add Rollup Visualizer

packages/documentation/pages/usage/components/form-fields.vue
Noticed that `KtFieldNumber` was positioned above `KtFieldMultiSelect` and was triggered
=> fix(documentation): Sort field names in selection alphabetically

packages/kotti-ui/source/kotti-breadcrumb/KtBreadcrumb.vue
Breadcrumb separators were not in line with the text.  
fixes #431
=> fix(#431): flexed breadcrumb items and aligned separators

packages/kotti-ui/source/kotti-translation/locales/ja-JP.ts
This is not a 'real' fix, but merely a small improvement, using the english translations instead of `TODO` placeholders for not translated Japanese
=> fix(442): replace TODOs with English translations for now

packages/kotti-ui/source/kotti-button/KtButton.vue
We set KtButton to be `inline-flex` items without taking care of vertical alignment.  This led to strange misalignments between buttons with differing content (like buttons with an icon vs buttons without an icon).
Setting `vertical-align` fixes this issue
Old, revolting, ridiculed with errors:
New, shiny, impeccable:
Closes #390
=> Resolve(#390): fix sizing issue via css vertical-align

package.json
On @carsoli’s setup, watching otherwise didn’t work. This should hopefully make watching more consistent.
Can potentially be removed once @carsoli has a new device, as the issue may never happen again. It’s unknown what exactly causes it.
=> hack(dx): Use Legacy Watch

packages/kotti-ui/source/kotti-comment/KtComment.vue, packages/kotti-ui/source/kotti-comment/components/CommentReply.vue
Follow-up PR to #454 
Changelog:
- remove `comment__avatar` class
- flex reply button text and icon in-line
- flex reply message and icon in-line
=> fix(454): remove avatar class, flex reply icons inline with button/text

packages/kotti-ui/source/kotti-translation/locales/ja-JP.ts
used deepL
- to translate strings for KtFields (Optional Label and Required Error Message)
- to translate strings for KtNavBar (Expand and Collapse tooltips, and QuickLinks link)
- to translate strings for KtFormSubmit (Popup Header title and Errors/Warnings Section titles)
better translations can land if a translator is there
=> chore(KtTranslationContext): add Japanese translations using deepL

packages/documentation/pages/usage/components/comment.vue, packages/kotti-ui/source/kotti-comment/KtComment.vue, packages/kotti-ui/source/kotti-comment/components/CommentReply.vue
Breaking Change: 
`allowChange` is no longer supported on `KtComment`
`isEditable`/`isDeletable` props are accepted now to separate permissions of deletion & editing
=> feat(#438): KtComment: replace `allowChange` with `isEditable`/`isDeletable`

packages/documentation/pages/usage/components/banner.vue, packages/documentation/pages/usage/components/steps.vue, packages/documentation/pages/usage/components/toaster.vue, packages/documentation/pages/usage/utilities.vue, packages/kotti-ui/source/kotti-style/utilities/_text.scss
Kotti’s language was always supposed to be en-US, so those are typos. There’s probably more, but they’re hard to find.
- `banner-grey` is now `banner-gray`
- `text-grey` is now `text-gray`
=> chore(@3yourmind/kotti-ui): Remove British English Typos

packages/documentation/pages/foundations/units.vue, packages/kotti-ui/source/kotti-style/_variables.scss, packages/kotti-ui/source/kotti-style/spacing.css
- `var(--unit-o)` is now `var(--unit-q)`
- `$unit-o` is now `$unit-q`
=> documentation(units): Add CSS Custom Properties, Mark SCSS as Deprecated, Rename Unit-O to Unit-Q

packages/kotti-ui/package.json
`esm` is already used for the command build:tokens (`node -r esm tokens/generate.js...`) but it was not an official dependency. We were just lucky it was there I guess.
=> dependencies(esm): add esm to devDependencies

.eslintrc.js, package.json, packages/documentation/components/ComponentInfo.vue, packages/documentation/pages/changelog.vue, packages/documentation/pages/foundations/units.vue, packages/documentation/pages/usage/utilities.vue, packages/documentation/pages/utilities.ts, packages/kotti-ui/source/kotti-button-group/types.ts, packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue, packages/kotti-ui/source/kotti-field-password/KtFieldPassword.vue, packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelect.vue, packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelect.vue, packages/kotti-ui/source/kotti-field-text/KtFieldText.vue, packages/kotti-ui/source/kotti-field/tests.ts, packages/kotti-ui/source/kotti-form-controller-list/KtFormControllerList.vue, packages/kotti-ui/source/kotti-form-controller-list/types.ts, packages/kotti-ui/source/kotti-form/tests.ts, packages/kotti-ui/source/kotti-navbar/types.ts, packages/kotti-ui/source/kotti-translation/types.ts, packages/kotti-ui/source/kotti-translation/utilities.ts, packages/kotti-ui/source/utilities.ts, yarn.lock
TS 4.4.2 is unfortunately not possible yet, as there’s this rollup+typescript bug that will most likely be fixed in TS 4.4.3:
https://github.com/rollup/plugins/issues/983
https://github.com/microsoft/TypeScript/issues/45633
Co-Authored-By: Moritz Vetter <16950410+HansAuger@users.noreply.github.com>
=> add-zod(1): Upgrade TS to 4.3.5

packages/documentation/components/ActionBar.vue, packages/documentation/data/menu.ts, packages/documentation/pages/foundations/icons/list.vue, packages/kotti-ui/source/kotti-avatar-group/index.ts, packages/kotti-ui/source/kotti-avatar/index.ts, packages/kotti-ui/source/kotti-banner/index.ts, packages/kotti-ui/source/kotti-breadcrumb/index.ts, packages/kotti-ui/source/kotti-button-group/index.ts, packages/kotti-ui/source/kotti-button/index.ts, packages/kotti-ui/source/kotti-field-date/index.ts, packages/kotti-ui/source/kotti-field-number/index.ts, packages/kotti-ui/source/kotti-field-password/index.ts, packages/kotti-ui/source/kotti-field-radio-group/index.ts, packages/kotti-ui/source/kotti-field-select/index.ts, packages/kotti-ui/source/kotti-field-text-area/index.ts, packages/kotti-ui/source/kotti-field-text/index.ts, packages/kotti-ui/source/kotti-field-toggle/index.ts, packages/kotti-ui/source/kotti-field/index.ts, packages/kotti-ui/source/kotti-filters/index.ts, packages/kotti-ui/source/kotti-form-controller-list/index.ts, packages/kotti-ui/source/kotti-form-controller-object/index.ts, packages/kotti-ui/source/kotti-form-submit/index.ts, packages/kotti-ui/source/kotti-form/index.ts, packages/kotti-ui/source/kotti-heading/index.ts, packages/kotti-ui/source/kotti-line/index.ts, packages/kotti-ui/source/kotti-modal/index.ts, packages/kotti-ui/source/kotti-navbar/index.ts, packages/kotti-ui/source/kotti-row/index.ts, packages/kotti-ui/source/kotti-translation/index.ts, packages/kotti-ui/source/types/kotti.ts
Another minor leftover from the add-zod PR. Basically just does this:
=> documentation(actionbar): Add Zod Tag to Documentation

packages/documentation/pages/foundations/icons/list.vue
Still compiled somehow, but yeah. It’s wrong.
=> fix(documentation): Typo in Import

packages/documentation/pages/usage/components/popover.vue
This PR is rebased on top of #515.
---
Not gonna fix the behavior for now, as there’s still the inactive branch of @carsoli and me trying to port `KtPopover` to tippy & TS.
=> fix(KtPopover): Warn About Highly Misleading Documentation

packages/documentation/pages/usage/components/popover.vue, packages/kotti-ui/source/kotti-popover/KtPopover.vue, packages/kotti-ui/source/kotti-popover/index.ts, packages/kotti-ui/source/kotti-popover/types.ts, packages/kotti-ui/source/types/kotti.ts
Rebased on top of #517.
---
Not adding TS now, as there’s still the open WIP branch of me and @carsoli trying to implement this.
- Drop support for `xxl` and `xxxl`
=> refactor(KtPopover): Add Types

packages/kotti-ui/source/kotti-comment/KtCommentInput.vue
Rebased on #526.
---
This actually also disables clicking the "disabled" button
=> fix(KtComment): Use Disabled Button instead of Opacity Hack

packages/kotti-ui/source/kotti-comment/components/CommentReply.vue
Rebased on #528.
---
This seems to only have existed to be added to the `key`
=> refactor(KtComment): Remove Type on Options

packages/documentation/pages/usage/components/form-fields.vue, packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelect.vue, packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelect.vue, packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelectRemote.vue, packages/kotti-ui/source/kotti-field-select/types.ts
IconTextItem already supported dataTest attributes, so I just pass them down
=> add-date-test-attributes-to-kt-field-single-select-remote

.github/labeler.yml, .github/workflows/labeler.yml
This will automatically add labels to PRs based on globs. Right now, this is only used for the `package:*` labels
=> ci(pull-requests): Add actions/labeler

packages/kotti-ui/source/kotti-comment/KtComment.vue, packages/kotti-ui/source/kotti-comment/types.ts, packages/kotti-ui/source/kotti-i18n/hooks.ts
=> Refactor kt comment topic/composition api comment

packages/kotti-ui/source/kotti-comment/KtComment.vue, packages/kotti-ui/source/kotti-comment/KtCommentInput.vue, packages/kotti-ui/source/kotti-comment/types.ts, packages/kotti-ui/source/kotti-i18n/locales/de-DE.ts, packages/kotti-ui/source/kotti-i18n/locales/en-US.ts, packages/kotti-ui/source/kotti-i18n/locales/es-ES.ts, packages/kotti-ui/source/kotti-i18n/locales/fr-FR.ts, packages/kotti-ui/source/kotti-i18n/locales/ja-JP.ts, packages/kotti-ui/source/kotti-i18n/types.ts
Now, the post/reply buttons are translated
as well as the placeholder
and the mini reply button on the comment reply
=> feat(KtComment): add translation context to KtComment

packages/documentation/pages/usage/components/form-fields.vue, packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue, packages/kotti-ui/source/kotti-field-number/constants.ts, packages/kotti-ui/source/kotti-field-number/types.ts, packages/kotti-ui/source/kotti-field-number/utilities.ts, packages/kotti-ui/source/kotti-field/tests.ts, packages/kotti-ui/source/kotti-form-controller-list/tests.ts, packages/kotti-ui/source/kotti-form-controller-object/tests.ts, packages/kotti-ui/source/kotti-form/tests.ts, packages/kotti-ui/source/kotti-i18n/KtI18nContext.ts, packages/kotti-ui/source/kotti-i18n/hooks.ts, packages/kotti-ui/source/kotti-i18n/types.ts, packages/kotti-ui/source/types/kotti.ts
Preliminary Steps before introducing `KtFieldCurrency`
As per description of #249, this is what is covered in this PR's scope:
- Make it customizable through a prop - and default to `3`
=> feat(#249): KtFieldNumber Enhancements

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue
the user-app can delete the component (destroys inputRef) on `input`
which would result in an `undefined` inputRef
> guard against this edge-case
Co-Authored-By: Florian Wendelborn <1133858+FlorianWendelborn@users.noreply.github.com>
=> fix(KtFieldNumber): avoid error when invoking focus on undefined inputRef

packages/kotti-ui/source/kotti-field-number/constants.ts, packages/kotti-ui/source/kotti-field-number/types.ts
accidentally thought it was not intentional
reverted support, and picked what's actually supported
=> revert(62b8fa62): KtFieldNumber should not support clear

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue, packages/kotti-ui/source/kotti-field-number/utilities.ts, packages/kotti-ui/source/utilities.test.ts, packages/kotti-ui/source/utilities.ts
now renamed to `isNumberInRange`
fixed import in KtFieldNumber
removed from utils from KtFieldNumber
reasoning: shared util across new fields
=> refact(isInRange): moved function to general utilties

packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue, packages/kotti-ui/source/kotti-field-number/constants.ts
..and would be removed on blur anyways.
unified naming of handlers, and removed unused ref from return
=> feat(KtFieldNumber): disallow user typing `+`, as it's pointless

packages/kotti-ui/source/kotti-field-toggle/KtFieldToggleGroup.vue
..as null
which means that on first render, if a value
..is still initialized as null, field.currentValue
could be `null`
therefore, guard against null[option.key]
=> fix(KtFieldToggleGroup): value prop is initialized

packages/kotti-ui/source/kotti-field-currency/KtFieldCurrency.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue, packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue, packages/kotti-ui/source/kotti-field-number/utilities.ts, packages/kotti-ui/source/kotti-field-password/KtFieldPassword.vue, packages/kotti-ui/source/kotti-field-radio-group/KtFieldRadioGroup.vue, packages/kotti-ui/source/kotti-field-select/KtFieldMultiSelect.vue, packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelect.vue, packages/kotti-ui/source/kotti-field-select/KtFieldSingleSelectRemote.vue, packages/kotti-ui/source/kotti-field-text-area/KtFieldTextArea.vue, packages/kotti-ui/source/kotti-field-text/KtFieldText.vue, packages/kotti-ui/source/kotti-field-toggle/KtFieldToggle.vue, packages/kotti-ui/source/kotti-field-toggle/KtFieldToggleGroup.vue, packages/kotti-ui/source/kotti-field/errors.ts, packages/kotti-ui/source/kotti-field/hooks.ts, packages/kotti-ui/source/kotti-field/tests.ts, packages/kotti-ui/source/kotti-field/types.ts, packages/kotti-ui/source/kotti-form-controller-list/tests.ts, packages/kotti-ui/source/kotti-form-controller-object/tests.ts, packages/kotti-ui/source/kotti-form/tests.ts
zod validates props now, with a readable error stack
therefore, all the validation logic for props
that were initially introduced can be dropped
=> chore(#592): delete isCorrectDataType check

packages/kotti-ui/source/kotti-field-currency/constants.ts, packages/kotti-ui/source/kotti-field-currency/types.ts
fixed by including the constant in the types file directly
Co-Authored-By: Florian Wendelborn <1133858+FlorianWendelborn@users.noreply.github.com>
=> fix(KtFieldCurrency): undefined regex on valueSchema

packages/documentation/pages/usage/layouts/introduction.vue
=> fix(docs/layouts): layouts/introduction had broken links in md

packages/kotti-ui/package.json, packages/yoco/package.json, yarn.lock
3.14.1 includes major performance improvements
Locally-done FT didn’t yield any errors. I was mostly concerned about `makeProps` as it uses `zod` internals, but since no errors were printed anywhere and the tests are passing I think those internals assumptions didn’t change.
=> chore(dependencies): Upgrade Zod

packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue, packages/kotti-ui/source/kotti-field-select/components/Options.vue
this is the previous behavior and the behavior as seen in other libraries
..so we brought it back
Co-Authored-By: Florian Wendelborn <1133858+FlorianWendelborn@users.noreply.github.com>
=> fix(KtFieldSingleSelect*): double-clicking selects same value

packages/kotti-ui/package.json, yarn.lock
commit `f59df39` on https://github.com/colinhacks/zod/releases/tag/v3.14.3 
...adds logic to optimize parsing of types by calling
...a lazy parser when nested schemas are defined.
Unfortunately, the context from the caller function (parser) is not bound
...properly and the lazy parser gets a partial context
This leads to an undefined access attempt because a necessary
...attribute is missing from the context in the lazy parser logic
in short, zod fails internally when parsing nested schemas starting version 3.14.3
=> fix(zod): force resolution to version 3.14.1 due to bug in 3.14.3

packages/kotti-ui/source/kotti-filters/components/FilterRow.vue
the root class changed after reimplementing the selects, and caused
...a margin ui bug
=> fix(KtFilters): remove undesired margin-bottom from kt-field-select

packages/kotti-ui/source/kotti-accordion/hooks.ts
Cancel animation to clear keyframeEffects and allow container to resize
=> fix(#647): fix KtAccordion with dynamic content not resizing 

packages/documentation/pages/usage/components/filters.vue, packages/documentation/pages/usage/components/form-fields.vue, packages/documentation/pages/usage/components/form.vue, packages/documentation/pages/utilities.ts, packages/kotti-ui/source/kotti-field-radio-group/KtFieldRadioGroup.vue, packages/kotti-ui/source/kotti-field-toggle/KtFieldToggleGroup.vue
Adds scoped slots to `KtFieldRadioGroup` and `KtFieldToggleGroup`
Not sure how to document the `option` binding in a good way though
Closes #295
=> feature(#295): Add KtFieldRadioGroup Scoped Slot Support

packages/documentation/pages/usage/components/accordion.vue, packages/kotti-ui/source/kotti-accordion/KtAccordion.vue, packages/kotti-ui/source/kotti-accordion/hooks.ts
Resolves #650 
Can be tested in documentation.
BREAKING CHANGE: isClosed becomes controllable and must always be maintained by parents
~~We usually don't rely on clients using `.sync` but in this case it reduces some boiler plate, so I thought it was good to mention in the docs.~~
=> 650 Accordion make close/open fully controllable

.github/workflows/ci.yml, .github/workflows/gh-pages.yml
Needed since more and more devtools will drop support for Node-v12
=> ci: use node 16 (LTS since Oct 2021) for pipelines

packages/documentation/pages/usage/components/modal.vue, packages/kotti-ui/source/kotti-modal/KtModal.vue
unless it changes and retriggers the watcher, the isOpen value
was dismissed in the first iteration
which led to a bug in announcementModal usages, where `isOpen` was true
and never changed throughout the lifecycle of the component.
Fix was to make the watcher immediate, keep track of the initial value
of `isOpen` and wait for tippy to be created and then show it
if the initial value was true.
=> fix(KtModal): does not show if isOpen prop is set to true initially

packages/documentation/pages/usage/components/form-fields.vue, packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue, packages/kotti-ui/source/kotti-field-select/types.ts
It is a desired feature by the user-app to clear the user query of the `KtFieldMultiSelect` after option selection.
Therefore, this PR introduces an optional prop `clearOnSelect`, which when set to true, clears the user query after every option selection.
=> feat(KtFieldMultiSelect): support clearOnSelect

packages/kotti-ui/source/kotti-field-select/components/Options.vue
It is a desired feature by the user-app that:
- When dropdown menu opens, the first item is automatically on focus → user can press Enter key and the item is selected
- User can start typing and the items are refined based on the search → first item of the results remains automatically on focus → user can press Enter key and the item is selected
Therefore, this PR changes the initial `hoveredIndex` from `-1` to `0`
=> feat(KtField*Select*): default hoveredIndex to `0` instead of `-1`

packages/kotti-ui/source/kotti-i18n/locales/de-DE.ts, packages/kotti-ui/source/kotti-i18n/locales/en-US.ts, packages/kotti-ui/source/kotti-i18n/locales/es-ES.ts, packages/kotti-ui/source/kotti-i18n/locales/fr-FR.ts, packages/kotti-ui/source/kotti-i18n/locales/ja-JP.ts
It has been requested by the Design team that when typing some text on a KtField*Select* component, if there are no options that match the text, to show the string `No results` instead of the previous one `No data`.
=> feat(KtField*Select*) Update from No Data string to No Results

packages/kotti-ui/source/kotti-field-select/components/ActionIcon.vue, packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue, packages/kotti-ui/source/kotti-field-select/hooks/use-select-tippy.ts
It is a desired feature by the user-app that:
When at least 1 item is selected, and on field focus or field mouse hover events, show “x” icon on the right side (next to the chevron, same behaviour of material UI autocomplete component)  → user can directly clean all selected items in 1 click
=> feat(KtField*Select*): Show clear icon next to chevron on field hover or focus

packages/documentation/pages/usage/components/breadcrumb.vue, packages/kotti-ui/source/kotti-breadcrumb/KtBreadcrumb.vue, packages/kotti-ui/source/kotti-breadcrumb/types.ts
- add a prop isDisabled for each step, default to false
- add a class kt-breadcrumb__text--is-disabled if isDisabled true
- execute onClick event only if step not disabled
- remove --breadcrumb-color-active and keep --breadcrumb-color-completed for both active and completed steps
- add color and font-weight properties when hovering over steps
- updated documentation for breadcrumbs
You can find the figma on the ticket B3-12163
=> feature(#676): adapt KtBreacrumbs with new design properties

packages/kotti-ui/source/kotti-style/_forms.scss, packages/kotti-ui/source/kotti-style/forms/_toggles.scss
- write back css for .form-checkbox .form-icon necessary in KtTable with selectable rows to avoid glitchy checkboxes in KtTable with selectable rows
=> fix(#674): re-add removed css properties for .form-checkbox .form-icon for KtTable

packages/kotti-ui/source/kotti-field/hooks.ts, packages/kotti-ui/source/kotti-field/types.ts
`dataTest` prop now is supported on all KtFields.
`useInputProps` initialise `data-test` property with the value of the `dataTest` prop if available.
=> KtField: support dataTest on input level of all KtFields

packages/documentation/components/ComponentInfo.vue, packages/kotti-ui/source/kotti-field-date/index.ts, packages/kotti-ui/source/kotti-field-select/index.ts, packages/kotti-ui/source/kotti-field-toggle/index.ts, packages/kotti-ui/source/types/kotti.ts
I noticed that not the links for the `KtField*Select*`s did not work, since the naming scheme of their file paths is not according to our convention. 
To fix this, I added an optional `componentFolder` field into the meta object. If it is set, this will be used instead of deriving the name from the component's name.
To test, look into the render, and check that for the select fields the links lead to the actual documentation pages.
Also, I did not check yet if there are any similar cases, will do it later. If something comes to mind, @ me
=> fix(docs): make folder name of components configurable

packages/kotti-ui/source/kotti-filters/utils.ts
Feat(KtFilters/KtFieldToggle): Initial default value is true, not possible to have boolean filter in null state.
When a user opens the filter popover and selects a boolean property filter: 
- By default the property is selected as true (checkbox is selected) → no interaction needed for the user
- When user clicks on the checkbox, state is changed to false (checkbox is unselected)
- It’s not possible to have the boolean filter in a null state
Closes [B3-12375](https://3yourmind.atlassian.net/browse/B3-12375)
[B3-12375]: https://3yourmind.atlassian.net/browse/B3-12375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(KtFilters/KtFieldToggle): Initial default value is true instead of null

packages/documentation/pages/usage/components/popover.vue, packages/kotti-ui/source/kotti-popover/KtPopover.vue, packages/kotti-ui/source/kotti-popover/components/IconTextItem.vue, packages/kotti-ui/source/kotti-popover/types.ts
replaced `isSelected` attribute on the options object with `isActive`
instead, `isSelected` represents that the checkbox is set to true and only makes sense if `areOptionsSelectable` is passed to `KtPopover`
> introduced `areOptionsSelectable` prop which enables showing the toggle fields ..and making the options selectable.
=> feat(KtPopover): extend options API to allow for checkboxes

packages/documentation/pages/usage/components/accordion.vue, packages/kotti-ui/source/kotti-accordion/KtAccordion.vue, packages/kotti-ui/source/kotti-accordion/types.ts, packages/kotti-ui/source/kotti-breadcrumb/KtBreadcrumb.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue, packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue, packages/kotti-ui/source/kotti-field-toggle/KtFieldToggleGroup.vue, packages/kotti-ui/source/kotti-field-toggle/types.ts
Adds data test attributes to some components:
* `KtAccordion`
* `KtFieldData`
* `KtBreadCrumb` - fix type
* `KtToggleGroup` - was not possible to set data-test for individual options.
* `KtFieldNumber` - for the decrease and increase button one each
=> Add some data test attributes

packages/documentation/pages/usage/components/popover.vue, packages/kotti-ui/source/kotti-popover/KtPopover.vue
Make popover open/close state a slot prop.
This is for cases where the trigger component should be displayed differently depending on if the popover is open or closed
=> feat(KtPopover): make open-close state of popover available

packages/kotti-ui/package.json
I'm aware that given the ^, it works anyways but I don't see why we should keep an old patch ersion
=> chore(dependencies): update @3yourmind/yoco's version to ^2.4.2

packages/documentation/pages/usage/components/popover.vue, packages/kotti-ui/source/kotti-popover/KtPopover.vue, packages/kotti-ui/source/kotti-popover/types.ts
This PR aims at disabling the trigger div in a KtPopover component when the prop isDisabled is set to true.
This is needed to disable the "more actions" buttons when all the action items are disabled and then prevent the opening of the popover containing the action items
=> feature(#667): disable the trigger div when the KtPopover is disabled

packages/documentation/pages/usage/components/filters.vue, packages/documentation/pages/usage/components/form-fields.vue, packages/documentation/pages/utilities.ts, packages/kotti-ui/source/kotti-field-radio-group/KtFieldRadioGroup.vue, packages/kotti-ui/source/kotti-field-toggle/KtFieldToggleGroup.vue, packages/kotti-ui/source/kotti-field-toggle/components/ToggleInner.vue
<label> was wrapped around the entire radio/toggle option (header + content slot), so clicking something in the content slot will activate the option. This will especially be a problem when there are [interactive elements in the option](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns)
`<label>` only wraps around the actual label. Also there is a new slot that is next to the label, that can be used if you need an interactive element in that area.
Layout breaks for long labels, radio buttons can be squished, radio button, checkbox, switches and the helptext icon are aligned to the center, which makes it look unusual
Elements are aligned to the first line of the option label
Text in the content slot now has a default style (smaller font-size) …
=> improvement(KtFieldToggleGroup/KtFieldRadioGroup): various fixes and improvements

packages/documentation/pages/usage/components/form-fields.vue, packages/documentation/pages/utilities.ts
A little adjustment to the form-fields path:
- Use `component` query parameter to set initially selected form field component
- when selecting a component, the url gets updated with the right query parameter
Intended effect: share and save specific urls for each component
=> docs(form-field): set initial field component with query parameter

packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue, packages/kotti-ui/source/kotti-field-select/hooks/use-select-tippy.ts
Clicking a disabled `KtField*Select` opens a tippy containing disabled menu items
With this change, click a disabled `KtField*Select` will result in no change in the UI
=> fix(KtFieldSelect): don't open tippy on a disabled select field

packages/kotti-ui/source/kotti-field-toggle/components/ToggleInnerSuffix.vue, packages/kotti-ui/source/kotti-field/KtField.vue
Small follow up to #729 
There was another misalignment similar to the ones fixed in #729 between a toggle's label and the label suffix (displayed if the `label` prop's value is `null`
This is how it used to look:
This is how it looks now:
=> fix(KtFieldToggle): align label suffix to label's first line

packages/documentation/pages/usage/components/card.vue, packages/kotti-ui/source/kotti-card/KtCard.vue
- fix issues with missing footer padding 
- fix/refact: remove margin/padding manipulation of elements used within the slot (should be controlled by user-app if needed)
- refact: unify slot implementation
- simplify classes that depend on image position
- introduce kt-card mod classes depending on image position to remove kt-card padding
- enhance docs by introducing a select for changeable imgPosition
- changing from md to vue syntax since we have the componentMetadata at the top of the doc page
=> fix(KtCard): footer padding/ padding between elements

packages/documentation/pages/usage/components/avatar.vue, packages/kotti-ui/source/kotti-avatar-group/KtAvatarGroup.vue, packages/kotti-ui/source/kotti-avatar-group/types.ts, packages/kotti-ui/source/kotti-avatar/KtAvatar.vue
KtAvatar/KtAvatarGroup: support `content` slot to allow custom popover usages
Breaking Change: tippy won't be shown if `isHoverable` is not passed
Enhance Docs of KtAvatar/KtAvatarGroup
=> feat(KtAvatar(Group)): add content slot and enhance docs

packages/documentation/pages/usage/components/avatar.vue, packages/kotti-ui/source/kotti-avatar/KtAvatar.vue
This MR aims to prevent KtAvatar image to grow in height bigger than its width. This was happening when siblings elements have a bigger height.
=> fix(KtAvatar): image & fallback to grow in height

packages/kotti-ui/source/kotti-field/errors.ts, packages/kotti-ui/source/kotti-field/hooks.ts, packages/kotti-ui/source/kotti-field/types.ts
This feature is needed because we programatically need to call `setValue` (returned on the field object from the `useField` hook)  - even when the field is disabled.
This option should be used with caution.
Additionally, the PR fixes a typo in the isDisabled error message.
=> feat(KtField): enable forceUpdate on useValue hook

packages/kotti-ui/source/kotti-style/_loadings.scss
I suddenly realized that the skeletons were not doing their shiny animation for my chromium based browser (brave)
This fixes the animation, I made sure that the animation also still works for both Safari and Firefox.
=> fix(chrome): make animation of skeletons work for chrome as well

packages/documentation/pages/usage/components/button.vue, packages/kotti-ui/source/kotti-button/KtButton.vue, packages/kotti-ui/source/kotti-button/types.ts
Support helpText prop exclusively for buttons with an undefined `label` prop (=buttons with icons only or nothing at all)
=> feat(KtButton): Add helptext prop for icon only buttons

packages/documentation/pages/usage/components/button.vue, packages/kotti-ui/source/kotti-button/KtButton.vue, packages/kotti-ui/source/kotti-button/types.ts
Add iconPosition prop, to allow users to add icon to the right of the label.
Default value is left.
=> feat(KtButton): Add iconPosition prop defaulted to left

packages/kotti-ui/source/kotti-comment/KtComment.vue, packages/kotti-ui/source/kotti-comment/components/CommentActions.vue, packages/kotti-ui/source/kotti-comment/components/CommentHeader.vue, packages/kotti-ui/source/kotti-comment/components/CommentReply.vue, packages/kotti-ui/source/kotti-comment/types.ts
As per the new design of KtComment, the popover for delete and edit actions is removed, and instead the action buttons are spread next to the reply..
All the actions are "KtButtons" of type 'text'
The Reply button only shows for the root comment because KtComment doesn't support nested comments beyond depth = 1 
> KtComment only supports one level of replies and therefore the reply button doesn't make sense on the reply comment
=> KtComment: replace KtPopover in CommentActions

packages/kotti-ui/source/kotti-button/KtButton.vue
The new div wrapper added to KtButton broke all inheritable attributes.
=> fix(kt-button): bind inheritable attributes to the button instead of the root node

packages/kotti-ui/source/kotti-field-file-upload/components/ItemLayout.vue
Fix file item layout to break long file names and prevent actions container from squishing the content
=> fix(kt-field-file-upload): fix file item layout

packages/documentation/pages/usage/components/button.vue, packages/kotti-ui/source/kotti-button/KtButton.vue, packages/kotti-ui/source/kotti-button/types.ts
Implements KtButton toggle:
Toggle button is only possible for types: default or text.
Should follow Figma designs: https://www.figma.com/file/0yFVivSWXgFf2ddEF92zkf/Kotti-Design-System?type=design&node-id=4528-10771&t=aooA0sTF2ETWwPx8-0
It adds one new props:
`toggleStatus`
=> Kt button toggleable type

packages/kotti-ui/source/kotti-button-group/KtButtonGroup.vue, packages/kotti-ui/source/kotti-button/KtButton.vue
Refact helpText feature in KtButton to fix issues caused by the introduction on a `div` wrapper around `<button />`. Also revert 2 fixes to styles and inherited properties attempting to fix some of the issues caused by the `div` wrapper.
Effectively: 
- Refact: e7e999b8a
- Revert: 6e6d2a1 and 55a46b5
Functional Test required:
1. In usage of KtButton, check that:
a. Under `Icon` section, `helpText prop can be passed to Icon only buttons that is displayed on button hover.` woks as expected.
b. Under `Button Group` section, buttons are rendered correctly, i.e. the borders and corners are rounded only on the external sides of the first and last buttons in the group.
2. In the usage of any other component that has a button disabled (e.g. in `KtComment`, the input text area should have the …
=> refact(kt-button): Refact helpText in KtButton

packages/documentation/pages/usage/components/filters.vue, packages/kotti-ui/source/kotti-filters/components/FilterRow.vue, packages/kotti-ui/source/kotti-filters/types.ts
Add `maximum` and `minimum` support (for `KtFieldNumber`) to float filter column.
=> feat(kt-filters): add maximum and minimum to float filters

packages/kotti-ui/source/kotti-comment/components/CommentTextArea.vue
This MR aims to fix the padding on CommentTextArea container:
Padding was set to: 12px on left and right and 16px on top. But it should be: 12px on top and 16px on left and right (as per design).
=> KtComment: Fix padding on CommentTextArea container

packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUpload.vue, packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUploadRemote.vue
Allow any status for existing items in value and add to preUploadedFilesIds only when status is equal to UPLOADED, UPLOADED_WITH_ERROR, or undefined
=> refact(kt-field-file-upload): refact pre uploaded files check

packages/kotti-ui/source/kotti-table/KtTable.vue
Fix styles for sort icon in KtTable column headers
Introduced by #787
=> fix(kt-table): fix KtTable sort icon style in column header

packages/kotti-ui/source/kotti-table/KtTable.vue
Fixes broken icons size in actions popover.
Introduced by #787
=> fix(kt-table): fix broken icons size inside row actions popover

packages/kotti-ui/source/kotti-field-date/mixins.scss
Fix broken table styles in KtFieldDate, KtFieldDateRange, KtFieldDateTime, KtFieldDateTimeRange
Introduced by #787
=> fix(kt-field-date): fix broken table styles 

packages/documentation/components/CodePreview.vue, packages/documentation/pages/usage/components/card.vue, packages/kotti-ui/source/kotti-card/KtCard.vue, packages/kotti-ui/source/kotti-card/index.ts, packages/kotti-ui/source/kotti-card/types.ts, packages/kotti-ui/source/kotti-style/_loadings.scss
Updated `KtCard` to make it ready for the Tile View of the catalog.
See different ACs in B3-13297.
Details:
- added props `primaryActionLabel` and `secondaryActionLabel` for the primary and secondary buttons
- I removed the `footer slot` as it complicates things. This is known to design. 
Why? Because we need to know if the card is of type "clickable" or "not-clickable (with buttons actions)".
The hovering and active style differs according to the card type. So, if we permit to add buttons in a footer's slot, we would have to read if there is any one in this slot to know if its a clickable card or not ==> too complicated for a small thing.
So primary and secondary actions are sent via props and the footer slot is removed.
- Header and body slots are still used so any additional skeleton …
=> feature(#788) : update KtCard component

packages/documentation/pages/usage/components/table.vue, packages/kotti-ui/source/kotti-table/types.ts
- Fix wrong type for KtTable prop `sortedColumns`
- Fix KtTable prop `remoteSort` wrongly documented as `sortRemote` in docs
=> fix(kt-table): fix sorted-columns type and docs

packages/documentation/pages/foundations/colors/list-of-colors.vue
Remove outdated colors in list-of-colors.vue
Follow-up to 359b86ef6c91784bf96180d57fc609cfde9694ca
=> chore(docs): remove outdated colors in list-of-colors.vue

packages/kotti-ui/source/kotti-field-file-upload/components/ItemLayout.vue
Fix bug where icon in file item description shrinks when description text wraps
=> fix(kt-field-file-upload): missing icon in file item description

packages/kotti-ui/source/kotti-card/KtCard.vue
This is a draft, do not merge for the moment.
Change to `KtCard`s : 
(1) - Give a default border to clickable cards to avoid increasing of size when hovering
=> feature(#801): give a default border to clickable cards

packages/kotti-ui/source/kotti-table/KtTable.vue, packages/kotti-ui/source/kotti-table/components/TableHeader.vue
This PR tries to fix the following problem:
Quicksort controls and table headers are overlapping
What happened:
[This PR](https://github.com/3YOURMIND/kotti/pull/787/files) moved table styles from a scss file into the table component. This changed the specificity of [this selector](https://github.com/3YOURMIND/kotti/blob/master/packages/kotti-ui/source/kotti-table/KtTable.vue#L333) for th `::v-deep table.kt-table th`. It is higher than [this selector](https://github.com/3YOURMIND/kotti/blob/master/packages/kotti-ui/source/kotti-table/components/TableHeader.vue#L202) so its instruction for padding is preferred.
Fix:
Put style that affects `th` into `TableHeader.vue` to make specifity for one clearer for devs and resolve this particular issue
Since this is a hotfix, I did not clean up the …
=> fix(TableHeader): move style into component to resolve specificity

packages/documentation/data/menu.ts, packages/documentation/pages/usage/components/form-fields.vue, packages/documentation/pages/usage/components/value-label.vue, packages/documentation/pages/utilities.ts, packages/kotti-ui/source/index.ts, packages/kotti-ui/source/kotti-field/mixins.scss, packages/kotti-ui/source/kotti-i18n/locales/de-DE.ts, packages/kotti-ui/source/kotti-i18n/locales/en-US.ts, packages/kotti-ui/source/kotti-i18n/locales/es-ES.ts, packages/kotti-ui/source/kotti-i18n/locales/fr-FR.ts, packages/kotti-ui/source/kotti-i18n/locales/ja-JP.ts, packages/kotti-ui/source/kotti-i18n/types.ts, packages/kotti-ui/source/kotti-value-label/KtValueLabel.vue, packages/kotti-ui/source/kotti-value-label/index.ts, packages/kotti-ui/source/kotti-value-label/types.ts, packages/kotti-ui/source/types/kotti.ts
Add KtValueLabel with support for:
- Text values only
- Help text (text and slot)
- Help description
- Unset text
- Validation text
- Default slot
=> feat(kt-value-label): add KtValueLabel

packages/kotti-ui/source/kotti-style/_variables.scss
Added a breakpoint 3x for 1920px to be used in the catalog tile view to make it responsive.
=> feature(#812): add breakpoint 3x for 1920 px

README.md
Not sure if `onrender` will ever be used again, but that link is dead for now.
=> fix: remove broken onrender link from README

packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue, packages/kotti-ui/source/kotti-tag/KtTag.vue
I am not sure why that original `text-transform: capitalize` was there. 
I kept the behavior around for the multi select field specifically, but not sure if it's desired. It can lead to inconsistencies like this.
I could also introduce a prop `isCapitalized` for this, but think it's overkill, as users can easily control this via CSS if desired.
=> fix(#833): remove capitalize transform

packages/kotti-ui/source/make-props.ts
```ts
type X = null | string | undefined
type INCORRECT_CHECK = X extends undefined ? true:never // never
type CORRECT_CHECK = undefined extends X ? true:never // true
```
We had a similar type check ternary on the "required" attribute that returned from the makeProps object.. the PR uses the correct check to fix it for all type usages of makeProps
=> fix(makeProps): required condition was swapped

packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue, packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUpload.vue, packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUploadRemote.vue, packages/kotti-ui/source/kotti-field-file-upload/components/DropArea.vue, packages/kotti-ui/source/kotti-field-file-upload/types.ts, packages/kotti-ui/source/kotti-field-select/hooks/use-select-tippy.ts, packages/kotti-ui/source/kotti-field-toggle/KtFieldToggle.vue, packages/kotti-ui/source/kotti-field/KtField.vue, packages/kotti-ui/source/kotti-field/hooks.ts, packages/kotti-ui/source/kotti-style/_loadings.scss
- prevent triggering setValue on isLoading for KtFieldToggle
- prevent triggering setValue on isLoading for KtFieldDate, KtFieldDateTime, KtFieldDateRange, KtFieldDateTimeRange
- prevent triggering tippy on isLoading for KtFieldSelect, KtFieldSelectRemote, KtFieldMultiSelect, KtFieldMultiSelectRemote
- throw on KtField if setValue is triggered while isLoading is true (to guide kotti devs)
- disable ktFieldUpload(Remote) input natively on isLoading (prevents opening system file explorer)
- breaking: remove isLoading skeleton margins to avoid weird visual jumping of the field when the isLoading is toggled
=> fix(KtFieldToggle/KtFieldSelects/KtFieldDates/KtFieldFileUpload): isLoading edge cases

packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue, packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUpload.vue, packages/kotti-ui/source/kotti-field-file-upload/KtFieldFileUploadRemote.vue, packages/kotti-ui/source/kotti-field-file-upload/components/DropArea.vue, packages/kotti-ui/source/kotti-field-file-upload/types.ts, packages/kotti-ui/source/kotti-field-number/KtFieldNumber.vue, packages/kotti-ui/source/kotti-field-select/components/ActionIcon.vue, packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue, packages/kotti-ui/source/kotti-field-select/hooks/use-select-tippy.ts, packages/kotti-ui/source/kotti-field-toggle/KtFieldToggle.vue, packages/kotti-ui/source/kotti-field-toggle/components/ToggleInner.vue, packages/kotti-ui/source/kotti-field-toggle/components/ToggleInnerSuffix.vue, packages/kotti-ui/source/kotti-field/KtField.vue, packages/kotti-ui/source/kotti-field/hooks.ts, packages/kotti-ui/source/kotti-field/types.ts
Refact `<label />` tag to contain only `label` and `options/required` texts and not the entire field to limit interactivity to the label (optional/required) and the input itself only.
=> refact(kt-field): refact label to reduce field interactivity

packages/kotti-ui/source/kotti-navbar/KtNavbar.vue, packages/kotti-ui/source/kotti-navbar/components/NavbarTooltip.vue
- icons had wrong font size <br> <img width="118" alt="Screenshot 2023-12-22 at 07 08 02" src="https://github.com/3YOURMIND/kotti/assets/16950410/f4dcca89-3cc6-4c35-b3a1-c9d7eaeb7be1">
- narrow state would affect mobile view <br> <img width="381" alt="Screenshot 2023-12-22 at 07 19 08" src="https://github.com/3YOURMIND/kotti/assets/16950410/4764e515-815b-4874-be4f-2105bf290aaa">
- user menu would be hidden behind main content <br> <img width="138" alt="Screenshot 2023-12-22 at 07 20 02" src="https://github.com/3YOURMIND/kotti/assets/16950410/c1c9054a-ec9c-42b4-bffb-921f41d028dc">
- navbar tooltips have a constant width <br> <img width="396" alt="Screenshot 2023-12-22 at 08 01 55" src="https://github.com/3YOURMIND/kotti/assets/16950410/f6bfa342-e1b1-4acf-9132-4cbc9e7daebd">
=> fix: resolve several visual bugs for narrow nav bar

packages/kotti-ui/source/kotti-comment/components/CommentTextArea.vue, packages/kotti-ui/source/kotti-comment/utilities.ts, packages/kotti-ui/source/kotti-field-inline-edit/KtFieldInlineEdit.vue, packages/kotti-ui/source/kotti-field-inline-edit/types.ts, packages/kotti-ui/source/kotti-field-inline-edit/utils.ts, packages/kotti-ui/source/kotti-field/KtField.vue, packages/kotti-ui/source/utilities.ts
- field is triggered when clicking on label (optional/required text) and input field only
- update :hover styles to show cursor: pointer when hovering on input field only
- allow KtField label selection on double/triple click
- fix cursor: pointer not showing when isMultiline is enabled
- fix setValue called on a disabled field when isLoading/isReadonly is enabled
- refact blurElement and move to root of kotti-ui
=> refact(kt-field-inline-edit): refact focusable elements

packages/documentation/pages/usage/components/form-fields.vue
remove unnecessary div around hideDropArea additional prop in the field documentation
=> fix(#864): remove div around additional props hideDropArea in documentation

packages/kotti-ui/source/make-props.test.ts, packages/kotti-ui/source/make-props.ts
makeProps was missing `default` on ReturnType
=> fix(makeProps): Properly Handle Types for defaults

packages/kotti-ui/source/kotti-field-currency/index.ts, packages/kotti-ui/source/types/index.ts
It’s relatively modern syntax and doesn’t always have perfect tooling support 
Removed because it caused problems in the Vue 2.7 branch
Co-Authored-By: Carol Soliman <17387510+carsoli@users.noreply.github.com>
=> refactor(kotti): Avoid Using `export * as` Syntax

packages/documentation/package.json, packages/documentation/pages/usage/components/field-inline-edit.vue, packages/kotti-ui/.unimportedrc.json, packages/kotti-ui/package.json, yarn.lock
No change in supported Vue versions as it was always intended to be 2.6.x.
- BREAKING: core-js@3.6.5 is now temporarily a dependency
- added `color` in `peerDependencies` as tokens needs it
- fixed weird import in KtFieldInlineEdit
Co-Authored-By: Carol Soliman <17387510+carsoli@users.noreply.github.com>
Caused-By: #877
This should fix the documentation 404 too
=> fix(dependencies): Declare core-js a Dependency of Kotti, Fix Vue Requirement to Be 2.6.x

packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue
typescript reaches maximum type size on the export and therefore `vue-tsc` can’t handle it in the template
Co-Authored-By: Carol Soliman <17387510+carsoli@users.noreply.github.com>
=> chore(kotti): as any element-ui refs

packages/documentation/pages/usage/components/loadings.vue
#850 caused a UI bug on docs for `loadings` component, since it removed `margin-bottom`
> introduce a class to add a row-gap between loading skeletons where needed
removal of margin-bottom was intentional
> see comments on original PR
=> feat(docs): add class to separate flex rows

.github/workflows/ci.yml, packages/vue-use-tippy/package.json, packages/vue-use-tippy/scripts/build.sh, packages/yoco/package.json, packages/yoco/scripts/build.sh
We had to do this because:
- nuxt@2 does not yet support reading "exports" from package json
- for an unknown reason nuxt resolved vue to an esm build in vue-use-tippy leading to two instances of vue being loaded (dual package hazard)
- Trying to fix the build issue itself yielded no results
- after many experiments the best approximation of a fix was to turn all
subpackages into modules
We also reduced the likelihood of this happening again by checking if the documentation builds without errors
=> fix(build): make yoco and vue-use-tippy esm by default

packages/kotti-ui/source/kotti-table/KtTable.vue
This reverts commit 0fb8d925b5d10a5ddbb8f022f983cf35a071bdf8.
This commit is unintentional. It was either created by a faulty rebase or by an unintended interference of eslint autofixing `vue/no-deprecated-dollar-scopedslots-api` rule
=> Revert "refact(KtTable): declare state types"

packages/kotti-ui/source/kotti-table/components/TableBody.ts, packages/kotti-ui/source/kotti-table/components/TableBodyExpandRow.ts, packages/kotti-ui/source/kotti-table/components/TableBodyLoadingRow.ts, packages/kotti-ui/source/kotti-table/components/TableRow.ts, packages/kotti-ui/source/kotti-table/components/TableRowCell.ts
Vue offers two different parameters to pass html attributes into rendered elements, `attrs` and `domProps`. But they are not interchangable, in fact each seems to accept a predefined set of attributes and will do nothing if the user passes an attribute that the paramenter does not accept. It is unclear what the logic behind this is, so the changes here have been found by experimentation
Edit:
After some investigation, this seems to be at least a hint at what is considered to be passed as `attrs` https://github.com/vuejs/vue/blob/13f4e7dc03e2caed900ac70ff8b8fe58dda45663/packages/server-renderer/src/util.ts#L27
=> fix(KtTable): use attrs instead of domProps for specific attributes

packages/vue-use-tippy/source/index.ts
In certain situations `import tippy from "tippy.js"` will not produce a function, because tippy will be imported as cjs when it should be imported as esm.
This hack tries to ensure correctness at runtime since a proper fix at build time has not been found and we prefer to keep both builds as export options.
=> hack(vue-use-tippy): make sure tippy is always a function

eslint.config.mjs, packages/kotti-ui/source/kotti-field-date/KtFieldDate.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateRange.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTime.vue, packages/kotti-ui/source/kotti-field-date/KtFieldDateTimeRange.vue, packages/kotti-ui/source/kotti-field-date/el-locales.d.ts
After investigating https://github.com/3YOURMIND/kotti/pull/952 and similar occurrences with packages that may be resolved as CJS, we pinned down the reason in node and how they are trying to make sense of importing CJS from ESM.
Resources:
- https://nodejs.org/docs/v20.15.0/api/esm.html#interoperability-with-commonjs
- https://github.com/nodejs/node/tree/main/deps/cjs-module-lexer
tl;dr: When in doubt, use default imports for dependencies that either use commonjs only, or do not declare "exports" in their `package.json`
In this PR we therefore enforce default imports for many of our dependencies, excluding the ones where we are empircally convinced that they are ok (like `zod` or `vue`)
=> chore(eslint): enforce default imports for dependencies that are not verifiably modern

packages/yoco/package.json
Tell node that this package supports importing svg files directly:
```ts
import charts from '@3yourmind/yoco/svg/charts.svg'
```
=> fix(exports): expose svg folder

packages/documentation/components/component-info/Slots.vue, packages/documentation/layouts/default.vue, packages/documentation/layouts/fullpage.vue, packages/documentation/pages/usage/components/accordion.vue, packages/documentation/pages/usage/components/table.vue, packages/kotti-ui/vite.config.ts
before this fix:
- runtime error "Detected Broken Build"
- various kotti components did not render in documentation
- some component usage pages did not even build
- notably everything worked fine on yoda's side
why this fix:
- turns out that nuxt imported element locales in the wrong format
-> tell vite to inline locales so we need not rely on importing it as dependency
=> fix(build): don't externalize element-ui's locales

packages/documentation/pages/usage/components/table.vue, packages/kotti-ui/package.json, packages/kotti-ui/source/kotti-table/KtTable.vue, packages/kotti-ui/source/kotti-table/logic/select.ts, packages/kotti-ui/source/kotti-table/logic/types.ts
after a thorough investigation this code turned out to be unused and safe to remove
=> refact(kt-table): remove $on call from KtTable

packages/kotti-ui/package.json, packages/kotti-ui/source/kotti-i18n/hooks.ts, packages/kotti-ui/vite.config.ts
create helper function to handle eventual default keys when importing element-ui's translation objects
=> fix(element-ui): externalize translations

internals/scripts/package.json, packages/kotti-ui/package.json, packages/yoco/package.json, yarn.lock
reasoning: (see also here -> <https://github.com/colinhacks/zod/issues/3435>) 
other zod 3.23 version may lead to typescript may lead to ts errors like: 
```error TS2589: Type instantiation is excessively deep and possibly infinite.```
=> dep(zod): lock version to v3.23.6

internals/scripts/package.json, packages/kotti-ui/package.json, packages/yoco/package.json, yarn.lock
after initially locking to v3.23.6 didn't fix the original issue and some subsequent experimentation, v3.22.5 turned out to be the right choice
see also -> <https://github.com/colinhacks/zod/issues/3435>
=> dep(zod): lock zod version to v3.22.5

packages/documentation/pages/usage/components/comment.vue, packages/kotti-ui/source/kotti-comment/KtComment.vue, packages/kotti-ui/source/kotti-comment/KtCommentInput.vue, packages/kotti-ui/source/kotti-comment/types.ts
This merge request intends to block comments into the internal mode meaning that the user cannot switch to public.
This prop is meaningful only if the property allowInternal is true.
=> feature(#970) : force internal comments for KtCommentInput (and KtComment)

packages/kotti-ui/source/index.ts, packages/kotti-ui/source/kotti-field-file-upload/index.ts, packages/kotti-ui/source/kotti-file-upload/KtFileUpload.vue, packages/kotti-ui/source/kotti-file-upload/components/UploadedFileItem.vue, packages/kotti-ui/source/kotti-file-upload/index.ts, packages/kotti-ui/source/kotti-file-upload/types.ts, packages/kotti-ui/source/kotti-file-upload/utilities.ts, packages/kotti-ui/source/types/kotti.ts
This is meant to replace KtFieldFileUploadRemote specifically, since it suffers from severe bugs since vue was updated to v2.7 and was hard to use even before that.
The PR has some open TODOs:
- The new component is missing proper documentation for the new component. 
- ~~`packages/kotti-ui/source/kotti-file-upload/types.ts` contains duplicated types with its counterparts from `kotti-field-file-upload`~~
- In general, one can consider to merge the two folders together, since KtFileUpload uses a lot of the components from `kotti-field-file-upload` - although it is not technically a field.
However, since this is urgent, I would propose to merge as is, I will deliver another PR amending the documentation as quickly as possible.
=> feat(KtFileUpload): create KtFileUpload component

packages/eslint-config/package.json, packages/eslint-config/source/index.ts
Since it’s autofixable it should be a warning not an error.
=> version(eslint-config@0.1.4): Make prettier/prettier a Warning

packages/kotti-ui/package.json, packages/kotti-ui/source/kotti-pagination/components/PaginationFlexible.vue
Note: we are using this import pattern `'lohash/xxx.js'` for all other imports as well. Not using it can lead to not found errors in certain setups.
=> fix(imports): use file path for lodash import

packages/kotti-ui/source/kotti-table/KtTable.vue, packages/kotti-ui/source/kotti-table/table/context.ts, packages/kotti-ui/source/kotti-table/table/hooks.ts
Unset successfullyDroppedColumnId after column re-order
=> fix(kt-table): unset successfullyDroppedColumnId after column re-order

packages/documentation/pages/usage/components/file-upload.vue, packages/kotti-ui/source/kotti-file-upload/components/UploadedFileItem.vue, packages/kotti-ui/source/kotti-file-upload/types.ts
In some cases we want to not display file size or do not have access to it. This MR removes the necessity to pass file's size to file info array entries
=> fix(KtFileUpload): optionally hide file size

packages/kotti-ui/source/shared-components/toggle-inner/ToggleInner.vue
ToggleInner's native input is visible in safari
=> fix(toggle-inner): hide input with display: none instead of width/height: 0

packages/kotti-ui/source/kotti-table/table/hooks.ts
make proper use of now indeterminate toggle state
=> feat(KtTable): make header toggle indeterminate if only some rows are selected

packages/kotti-ui/source/kotti-field-select/components/ActionIcon.vue, packages/kotti-ui/source/kotti-field-select/components/GenericSelectField.vue
Make the actions container fixed width when clear icon is available to prevent the selected content from jumping around when clear icon shown on hover.
=> refact(KtFieldSelects): actions container has now a fixed width when the clear icon is available
